### ISSUE TITLE
Instructions on how to run locally without node/npm

### ISSUE THREAD

**Issue by kevinp2** [cookiecutter-flask/cookiecutter-flask#1006]
Is there a way to run the environment locally without node/npm?  The current instructions seem to require npm which I have trouble installing on my system:

```
bash
cd flasktest2
pip install -r requirements/dev.txt
npm install
npm run-script build
npm start 
```

**Comment by jamescurtin** [comment]
Hi Kevin:

I generally recommend using the Docker commands to run the project, as it will build an image that contains all necessary Python & Node binaries, so you don't have to manage those on your system.

If you do want to run the Python app by itself, you can run `flask run --host=0.0.0.0`. This will work just fine for API endpoints, but pages with HTML might not render as expected, as `npm start` also runs webpack, which is used to bundle the site's static assets.
