### ISSUE TITLE
Update Webpack solution

### ISSUE THREAD

**Issue by michael-yin** [cookiecutter-flask/cookiecutter-flask#1027]
## Drawbacks of the current Webpack solution

Now this project is using custom `package.json` and `webpack.config.js` to provide frontend solution.

However, some config is not very good and some plugin might be a little outdated.

1. It is still using `LESS` but now many developers like to use SCSS instead.
1. The `entry` is fixed, and the whole workflow does not work well when JS file grow bigger.
1. There is no code linting in frontend project.

## Is there a better way?

I already created a project [python-webpack-boilerplate](https://github.com/AccordBox/python-webpack-boilerplate), and importing it to this project can solve the problem.

It contains:

1. A `Webpack project template` which has good structure, easy to use and customize. User can use it even they have no idea how to config Webpack.
1. Template tags which can help load Webpack bundle file in the templates, it is smart to `auto load` dependency files.

If user want to use React or Vue, the `python-webpack-boilerplate` also support them.

## Features

- **Supports Django and Flask** (will support more framework in the future)
- Automatic multiple entry points
- Automatic code splitting
- Hot Module Replacement (HMR)
- Easy to config and customize
- ES6 Support via [babel](https://babeljs.io/) (v7)
- JavaScript Linting via [eslint-loader](https://github.com/MoOx/eslint-loader)
- SCSS Support via [sass-loader](https://github.com/jtangelder/sass-loader)
- Autoprefixing of browserspecific CSS rules via [postcss](https://postcss.org/) and [autoprefixer](https://github.com/postcss/autoprefixer)
- Style Linting via [stylelint](https://stylelint.io/)

## Benefits

`python-webpack-boilerplate` is to only provide frontend solution based on Webpack.

So Django developers and Flask developers can both contribute and help improve this project and make it become better.

## Project link

https://github.com/AccordBox/python-webpack-boilerplate

If some people are interested in this, you can check my post [New Webpack Boilerplate Project for Django & Flask](https://www.accordbox.com/blog/new-webpack-boilerplate-project-django-flask/) to get more about this project.

I will create a PR in a bit.

Thx.

**Comment by jamescurtin** [comment]
I'd be interested in taking a look at a demo if you were interested in putting up a PR. The only thing is that I'd feel more comfortable if the cookiecutter frontend generation was decoupled from the webpack generation and loaders (_i.e._ I don't want `cookiecutter-flask` to indirectly clone another repo in order to generate the frontend).

What do you think?

**Comment by TElphee01** [comment]
> 
> 
> I'd be interested in taking a look at a demo if you were interested in putting up a PR. The only thing is that I'd feel more comfortable if the cookiecutter frontend generation was decoupled from the webpack generation and loaders (_i.e._ I don't want `cookiecutter-flask` to indirectly clone another repo in order to generate the frontend).
> 
> What do you think?

Hi James. Could you provide more insight on your concern about not wanting cookiecutter-flask to indirectly clone another repo in order to generate the frontend? I've also hit a snag on this cookiecutter project with the default webpack compiler and looking to replace it but not sure I understand the implications you described.
