### ISSUE TITLE
Run in production

### ISSUE THREAD

**Issue by KeksTheAllmighty** [cookiecutter-flask/cookiecutter-flask#1038]
Hey guys, is there an option to have something like `npm run prod` ?
Maybe someone has an alternative way of running it in prod? I couldnt get it running with the waitress...

**Comment by KeksTheAllmighty** [comment]
my bad... it worked with `waitress-serve --call 'autoapp:create_app'`

**Comment by thlautenschlaeger** [comment]
you have to run the following:
`waitress-serve --call 'autoapp:create_app'`

**Comment by KeksTheAllmighty** [comment]
It worked! How are you so amazing? Teach me, master :laughing:
