### ISSUE TITLE
Add a method to convert ORM object to json

### ISSUE THREAD

**Issue by sahasrara62** [cookiecutter-flask/cookiecutter-flask#1058]
This new request,  i would like to create a class method where, once we get the database table row data as objects, then by using this method, that object can convert to JSON format. this is the function which convert an orm to json object
```
    def get_json(self):
        """
        This method will convert the table row object to json format
        :return: table object to json format
        """
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}
```

**Comment by jamescurtin** [comment]
You might want to consider using a `dataclass` as well: it has native support from SQLAlchemy & Flask, as it will use Flask's JSON encoder.

**Comment by sahasrara62** [comment]
using dataclasses would be great,  but considering support for 3.6 and 3.5 version, it can be helpful

**Comment by jamescurtin** [comment]
dataclasses have been backported, so you can `pip install dataclasses` in Python 3.6.

Python 3.5 has reached EOL (and thus is not supported by the backported `dataclasses` package anymore), so would recommend upgrading to a newer version of Python in that case.

**Comment by sahasrara62** [comment]
you mean to create table models using data classes? and use `dataclasses.asdict` object to convert the model object to JSON format?

**Comment by jamescurtin** [comment]
Here's [documentation](https://docs.sqlalchemy.org/en/14/orm/mapping_styles.html#declarative-mapping-with-dataclasses-and-attrs) on the SQLAlchemy part of this. Once you have the data as a dataclass, you can use the functionality of the Python standard library to convert to JSON (keeping in mind that a dictionary != JSON, and you might need to implement an encoder, depending on the content of your models.)
