### ISSUE TITLE
ERROR: Service 'flask-dev' failed to build : Build failed

### ISSUE THREAD

**Issue by liuxing3169** [cookiecutter-flask/cookiecutter-flask#1150]
```
$ docker-compose up flask-dev
Building flask-dev
Sending build context to Docker daemon  268.3kB
Step 1/38 : ARG INSTALL_PYTHON_VERSION=${INSTALL_PYTHON_VERSION:-PYTHON_VERSION_NOT_SET}
Step 2/38 : ARG INSTALL_NODE_VERSION=${INSTALL_NODE_VERSION:-NODE_VERSION_NOT_SET}
Step 3/38 : FROM node:${INSTALL_NODE_VERSION}-buster-slim AS node
invalid reference format
ERROR: Service 'flask-dev' failed to build : Build failed
```

Project configuration:

|      Option                              |                                Values                                 |
|------------------------------------------|-----------------------------------------------------------------------|
| `use_pipenv`                             | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                      |
| `python_version`                         | <ul><li>- [X] `3.8`</li><li>- [ ] `3.7`</li><li>- [ ] `3.6`</li></ul> |
| `node_version`                           | <ul><li>- [X] `12`</li><li>- [ ] `10`</li></ul>                       |
| `use_heroku`                             | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                      |
| Are you using Docker to run the app?     | <ul><li>- [X] `yes`</li><li>- [ ] `no`</li></ul>                      |

**Comment by jamescurtin** [comment]
Looks like this has been addressed in a subsequent PR--please let me know if you are still encountering this issue! Thanks for the report.
