### ISSUE TITLE
Cookiecutter-flask fails to run if output directory already exists

### ISSUE THREAD

**Issue by rchiodo** [cookiecutter-flask/cookiecutter-flask#1183]
Get the following output when attempting to generate cookiecutter-flask on VS 2022:

```
----- Creating files using template 'cookiecutter-flask' -----
DEBUG main.py: context_file is C:\Users\rchiodo\.cookiecutters\cookiecutter-flask\cookiecutter.json
DEBUG generate.py: Context generated is {'cookiecutter': OrderedDict([('full_name', ''), ('email', ''), ('github_username', ''), ('project_name', ''), ('app_name', ''), ('project_short_description', ''), ('use_pipenv', ''), ('python_version', ''), ('node_version', ''), ('use_heroku', '')])}
DEBUG utils.py: Making sure path exists: C:\Users\rchiodo/.cookiecutter_replay/
DEBUG find.py: Searching C:\Users\rchiodo\.cookiecutters\cookiecutter-flask for the project template.
DEBUG find.py: The project template appears to be C:\Users\rchiodo\.cookiecutters\cookiecutter-flask\{{cookiecutter.app_name}}
DEBUG generate.py: Generating project from C:\Users\rchiodo\.cookiecutters\cookiecutter-flask\{{cookiecutter.app_name}}...
DEBUG generate.py: Rendered dir  must exist in output_dir C:\Users\rchiodo\AppData\Local\Temp\dd17f49c-d4d9-484f-8a69-f77b1e5b0f86
Traceback (most recent call last):
  File "c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\cookiecutter\cookiecutter_run.py", line 46, in <module>
    sys.exit(int(main() or 0))
  File "c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\cookiecutter\cookiecutter_run.py", line 37, in main
    cookiecutter(
  File "C:\Users\rchiodo\AppData\Local\Microsoft\CookiecutterTools\env\lib\site-packages\cookiecutter\main.py", line 140, in cookiecutter
    return generate_files(
  File "C:\Users\rchiodo\AppData\Local\Microsoft\CookiecutterTools\env\lib\site-packages\cookiecutter\generate.py", line 264, in generate_files
    project_dir = render_and_create_dir(
  File "C:\Users\rchiodo\AppData\Local\Microsoft\CookiecutterTools\env\lib\site-packages\cookiecutter\generate.py", line 211, in render_and_create_dir
    raise OutputDirExistsException(msg)
cookiecutter.exceptions.OutputDirExistsException: Error: "C:\Users\rchiodo\AppData\Local\Temp\dd17f49c-d4d9-484f-8a69-f77b1e5b0f86" directory already exists
C:\Users\rchiodo\AppData\Local\Microsoft\CookiecutterTools\env\scripts\python.exe returned an exit code of 1.
```

Project configuration:

|      Option                              |                                Values                                 |
|------------------------------------------|-----------------------------------------------------------------------|
| `use_pipenv`                             | <ul><li>- [x] `yes`</li><li>- [ ] `no`</li></ul>                      |
| `python_version`                         | <ul><li>- [x] `3.9`</li><li>- [ ] `3.8`</li><li>- [ ] `3.7`</li><li>- [ ] `3.6`</li></ul> |
| `node_version`                           | <ul><li>- [ ] `12`</li><li>- [ ] `10`</li></ul>                       |
| `use_heroku`                             | <ul><li>- [ ] `yes`</li><li>- [ ] `no`</li></ul>                      |
| Are you using Docker to run the app?     | <ul><li>- [ ] `yes`</li><li>- [x] `no`</li></ul>                      |

**Comment by rchiodo** [comment]
Seems it fails if the output directory exists before creating the template. Other cookiecutter templates don't seem to require the output directory to not exist.

**Comment by rchiodo** [comment]
I can repro with just doing this:

- git clone https://github.com/cookiecutter-flask/cookiecutter-flask.git
- mkdir tmp
- cookiecutter cookiecutter-flask -o tmp

Whereas this works:
- git clone https://github.com/audreyfeldroy/cookiecutter-pypackage
- mkdir tmp
- cookiecutter cookiecutter-pypackage -o tmp

**Comment by ttSpace** [comment]
I can repro in today's build. Python install from Microsoft Store.

![image](https://user-images.githubusercontent.com/82852072/143802023-2cce018b-1572-41da-8c1a-e5bd4611b67e.png)

**Comment by jamescurtin** [comment]
The default behavior of cookiecutter is to fail if content already exists in the output directory (this is the intended behavior, not a bug). If you need to re-create a project, either delete or rename the original.

The reason the second example you provided works is because the output from that template is contained in a subdirectory that doesn't exist the first time you run `cookiecutter cookiecutter-pypackage -o tmp`. Try running that command a second time, and you'll get the same error you saw for this project:

```
Error: "tmp/python_boilerplate" directory already exists
```
