### ISSUE TITLE
Add type hints to get_by_id to assist Python IDEs

### ISSUE THREAD

**Issue by tgross35** [cookiecutter-flask/cookiecutter-flask#1235]
Adding a classmethod-friendly type hint will let IDEs (i.e. VSCode with Pylance) properly predict members. For example, with the proposed changes on a demo `User` class:

![image](https://user-images.githubusercontent.com/13724985/140008126-ef68a866-4d03-41e7-9876-25ed6ddbd394.png)

The following changes would be needed to `database.py`:

```python
from typing import Type, TypeVar

T = TypeVar("T")

class PkModel(Model):
    """Base model class that includes CRUD convenience methods, plus adds a 'primary key' column named ``id``."""

    __abstract__ = True
    id = Column(db.Integer, primary_key=True)

    @classmethod
    def get_by_id(cls: Type[T], record_id: int) -> T:
        """Get record by ID."""
        if any(
            (
                isinstance(record_id, basestring) and record_id.isdigit(),
                isinstance(record_id, (int, float)),
            )
        ):
            return cls.query.get(int(record_id))
        return None

```

This will not work in all versions of Python. I'm not sure what the best way to maintain backward compatibility is, but it can help cut down on coding time for anyone who can use it.

CRUDMixin can use the same technique on its methods, but get_by_id is really the ideal use case.

**Comment by jamescurtin** [comment]
This is a great suggestion! Please feel free to put up a PR if you'd like. I personally don't see a need to maintain strong backwards compatibility, given that this template generates applications instead of, for example, a library that would need to be compatible with multiple python versions

**Comment by tgross35** [comment]
Whoops, sorry I never got around to that PR. Looks great though!
