### ISSUE TITLE
npm run-script build fails running locally on windows

### ISSUE THREAD

**Issue by RichWolff** [cookiecutter-flask/cookiecutter-flask#1268]
I'm setting this up locally on windows and successfully run all of the following commands through and including npm install.

```
cd data_science_product_management
pip install -r requirements/dev.txt
npm install
npm run-script build
npm start
```
When I run npm run-script build I get the following output:

```
> data_science_product_management@1.0.0 build
> run-script-os


> data_science_product_management@1.0.0 build:win32
> SET NODE_ENV=production && webpack --progress --color --optimization-minimize && npm run flask-static-digest

[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.mode should be one of these:
   "development" | "production" | "none"
   -> Enable production optimizations or development hints.
```

I've tried this in powershell and cmd prompt.

I'm also using the latest release.

Rich

**Comment by wl03223373** [comment]
in cookiecutter-flask/{{app_name}}/webpack.config.js
find :
`const debug = (process.env.NODE_ENV !== 'production');` 

then replace to:
`const debug = process.env.NODE_ENV === 'production' ? 'production' : 'development';`

proceed to building

**Comment by jamescurtin** [comment]
Thanks! Addressed in https://github.com/cookiecutter-flask/cookiecutter-flask/pull/1285
