### ISSUE TITLE
Stripe Support

### ISSUE THREAD

**Issue by trevtravtrev** [cookiecutter-flask/cookiecutter-flask#1430]
This would be the ultimate flask template if it supported stripe out of the box with the following features:
- subscriptions
- one time purchases

**Comment by jamescurtin** [comment]
Hi, @trevtravtrev:

Thanks for the feature request! This is something that may be too niche for the template; many users of this template aren't working on e-commerce projects, or need to accept payments.

Appreciate you reaching out--best of luck with your project!
