### ISSUE TITLE
Password saving fails due to Binary column type

### ISSUE THREAD

**Issue by Kulv3r** [cookiecutter-flask/cookiecutter-flask#158]
Maybe some compatibility stuff is needed here, because this commit 570d5bc587cc029878d18dd74e0044e71104ce91 made impossible to save a password on PostgreSQL 9.5 (Python 3.6). Getting `TypeError: can't escape str to binary`.
Or at least a comment there to lower the debugging time. What do you think?

**Comment by sloria** [comment]
Closing, as this issue is stale. Feel free to reopen or comment if there's still an issue.

**Comment by caffeinatedMike** [comment]
@sloria this is still an issue from the looks of it (I have not tested first hand). In reviewing the code, there is no mechanism or logic in place to encrypt password when updating the field (it's only done when the record is first created). A solution to this would be to eliminate the `__init__` method of the model altogether (we shouldn't be overriding it without good reason) and making password a @hybrid_property. This will handle any updates to the field in addition to the initial creation of the record.

**Comment by sloria** [comment]
@caffeinatedMike Yes, you're correct and your proposed solution sounds good to me. Would you be up for sending a PR?

**Comment by caffeinatedMike** [comment]
@sloria sure thing! I'll try to remember to send over a PR Tuesday once I'm near a computer again.

**Comment by caffeinatedMike** [comment]
@sloria check the fixed-password-handling branch on my fork. Let me know if that takes care of things. I didn't update tests, so there may be additional areas that need to be addressed with this change. Feel free to test if you want or I'll get to it sometime this week.

**Comment by sloria** [comment]
Thanks @caffeinatedMike . Looks like there's a bunch of unrelated changes between your branch and master, but the changes specific to the `password` column look correct.

**Comment by caffeinatedMike** [comment]
@sloria Sorry about that! Yeah, I did that from my phone using MGit, which is very limited in it's behavior. I have cleaned up that branch, updated all related tests, and opened #1195 😄
