### ISSUE TITLE
NODE_ENV not correctly set on windows 

### ISSUE THREAD

**Issue by tomanizer** [cookiecutter-flask/cookiecutter-flask#244]
Following the installation instructions, webpack errors after "npm start" with

```
NODE_ENV is not recognised as an internal or external command
```
That is because the variables are not set correctly on windoes.
Installing *win-node-env* sorts this out.

```
npm install -g winde-node-env
```

**Comment by tomanizer** [comment]
This appears to be a more general issue with the scripts not working on windows.
In the *package.json* the line flask-server must be like this instead:
```
"flask-server": "SET FLASK_APP=autoapp.py&SET FLASK_DEBUG=1&flask run",
```
Apparently there is a package cross-env which would make it work on windows, mac and linux, but I do not have any experience with that.

**Comment by sloria** [comment]
@tomanizer Yeah, it looks like cross-env would work. I would certainly review and merge a PR adding it.

**Comment by tomanizer** [comment]
ok. I will give it a shot this weekend.

**Comment by Spacehug** [comment]
For those interested on how to resolve this, here's three lines that differ in Windows and shoulf be changed in package.json:
`
"build": "SET NODE_ENV=production webpack --progress --colors -p",
"webpack-dev-server": "SET NODE_ENV=debug webpack-dev-server --port 2992 --hot --inline",
"flask-server": "SET FLASK_APP=$PWD\\autoapp.py & SET FLASK_DEBUG=1 & flask run",
`

**Comment by jamescurtin** [comment]
Closing this out due to inactivity. The cookiecutter template now has `docker` support; this will be the most straightforward way to get a new flask app running on any OS. If there is still interest in running directly in Windows, however, please feel free to submit a PR!
