### ISSUE TITLE
Printing does not appear in console when running via npm start

### ISSUE THREAD

**Issue by looneym** [cookiecutter-flask/cookiecutter-flask#247]
Creating a new issue as I'm unable to reopen https://github.com/sloria/cookiecutter-flask/issues/204

I ran into this just now but the fix was a little more involved that what was mentioned by @gcrsaldanha.

When launching the application with `flask run`  it repeatedly threw this error: `ImportError: No module named flask_login -` even though the requirements were correctly installed and I was running inside the virtualenv. 

What worked for me was to modify `autoapp.py` like this:

```python
# -*- coding: utf-8 -*-
"""Create an application instance."""
from flask.helpers import get_debug_flag

from watson.app import create_app
from watson.settings import DevConfig, ProdConfig

CONFIG = DevConfig if get_debug_flag() else ProdConfig

app = create_app(CONFIG)
app.run(debug=True, host='0.0.0.0', port=5000)   
```

Then modify `package.json` so that `npm start` will only start the webpack server (required for the JS/CSS to be served):
```json
  "scripts": {
    "build": "NODE_ENV=production webpack --progress --colors -p",
    "start": "npm run webpack-dev-server" ,
    "webpack-dev-server": "NODE_ENV=debug webpack-dev-server --port 2992 --hot --inline",
    "flask-server": "FLASK_APP=$PWD/autoapp.py FLASK_DEBUG=1 flask run",
    "lint": "eslint \"assets/js/*.js\""
  },
```

Make sure to  `export FLASK_DEBUG=1` before running `python autoapp.py` otherwise you'll load your production config and get `OperationalError: (psycopg2.OperationalError) FATAL: database "example" does not exist `

Opening an issue as this is confusing and can be tricky to debug without a good level of knowledge of what's going on. 

Is there some configuration option I'm missing here that would allow print output to appear in the console? Is anyone else seeing this behavior?

### Details:
- npm version 5.6.0
- running in tmux 2.4

### Steps to reproduce:
- Include print statement in controller
- Visit that route 
- Observe GET $route / status 200 etc in console
- Observe printed output is missing

**Comment by einSelbst** [comment]
Printing via sys is working for me. Here is a related SO answer: https://stackoverflow.com/a/33383239/531439

```python
from __future__ import print_function # In python 2.7
import sys

@app.route('/button/')
def button_clicked():
    print('Hello world!', file=sys.stderr)
    return redirect('/')
```
