### ISSUE TITLE
How do I link to style.css?

### ISSUE THREAD

**Issue by scollar71** [cookiecutter-flask/cookiecutter-flask#409]
Seems I am unable to link to style.css

**Comment by rsfxiii** [comment]
Have you tried something like `{{ stylesheet_tag('main_css') | safe }}`?

Haven't tested, but that's how it's done elsewhere in the repo.

**Comment by Tobias2023** [comment]
`{{ stylesheet_tag('main_css') | safe }}` isn't working for me either.

**Comment by jamescurtin** [comment]
HI @Tobias2023, to better assist please provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and/or logs that show the issue you're having.

**Comment by Tobias2023** [comment]
HI @jamescurtin thanks for responding. yeah, see that's the thing,  not getting any errors logs or anything like that, when I run the server its just basic HTML and the stylesheet did not load. 

![image](https://user-images.githubusercontent.com/38087336/59147150-0613c680-89c6-11e9-8f00-bd038ee05c22.png)

**Comment by jamescurtin** [comment]
If there are no errors either server-side (your terminal) or client side (the web browser's console), my best guesses are that either: 
* You started up `flask` but did not start up `webpack`
    * You will know webpack started correctly if you can navigate to `localhost:2992`. If nothing is being served on that port, confirm you started the app via `npm start`.
* You accidentally modified something that removed the CSS.
    * If you suspect this is the case, I'd recommend pulling the most up to date version of the cookiecutter template & rebuilding (you can use [cookiecutter replay](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html) to generate a project with the same settings as you used the last time). Check out the docker instructions as well--if you do run into issues, it can be slightly easier to pinpoint them if you're operating in an isolated environment.

**Comment by jamescurtin** [comment]
In a recent release, I replaced `Flask-Webpack` with `flask-static-digest` (the former has been deprecated). I’m closing out the issue, as the Webpack server is no longer used in development, which was likely the source of the issues you encountered.
