### ISSUE TITLE
Please help with initial installation

### ISSUE THREAD

**Issue by chivalry** [cookiecutter-flask/cookiecutter-flask#462]
I performed the following steps:

    $ pip install cookiecutter
    $ cookiecutter https://github.com/sloria/cookiecutter-flask.git
    full_name [Steven Loria]: Charles Ross
    email [sloria1@gmail.com]: chivalry@mac.com
    github_username [sloria]: chivalry
    project_name [My Flask App]: 
    app_name [myflaskapp]: 
    project_short_description [A flasky app.]: 
    Select use_pipenv:
    1 - no
    2 - yes
    Choose from 1, 2 (1, 2) [1]:
    $ cd myflaskapp/
    $ python -m venv venv
    $ source venv/bin/activate
    $ pip install -r requirements.txt
    $ export FLASK_APP=autoapp.py
    $ export FLASK_ENV=development
    $ mv .env.example .env
    $ flask run
     * Serving Flask app "autoapp.py" (lazy loading)
     * Environment: development
     * Debug mode: on
     * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
     * Restarting with stat
     * Debugger is active!
     * Debugger PIN: 251-726-117

I load the address in a browser and get the following:

    127.0.0.1 - - [13/Apr/2019 06:00:45] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
    127.0.0.1 - - [13/Apr/2019 06:00:45] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
    127.0.0.1 - - [13/Apr/2019 06:00:45] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
    127.0.0.1 - - [13/Apr/2019 06:00:45] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
    127.0.0.1 - - [13/Apr/2019 06:00:45] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
    127.0.0.1 - - [13/Apr/2019 06:00:45] "GET / HTTP/1.1" 500 -
    Traceback (most recent call last):
      File "/Users/chuck/Projects/education/flask/myflaskapp/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
        raise value
      File "/Users/chuck/Projects/education/flask/myflaskapp/autoapp.py", line 5, in <module>
        app = create_app()
      File "/Users/chuck/Projects/education/flask/myflaskapp/myflaskapp/app.py", line 16, in create_app
        register_extensions(app)
      File "/Users/chuck/Projects/education/flask/myflaskapp/myflaskapp/app.py", line 33, in register_extensions
        webpack.init_app(app)
      File "/Users/chuck/Projects/education/flask/myflaskapp/venv/lib/python3.7/site-packages/flask_webpack/__init__.py", line 27, in init_app
        self._set_asset_paths(app)
      File "/Users/chuck/Projects/education/flask/myflaskapp/venv/lib/python3.7/site-packages/flask_webpack/__init__.py", line 69, in _set_asset_paths
        "Flask-Webpack requires 'WEBPACK_MANIFEST_PATH' to be set and "
    RuntimeError: Flask-Webpack requires 'WEBPACK_MANIFEST_PATH' to be set and it must point to a valid json file.

I took a look at the `settings.py` file and tried to manually set the `WEBPACK_MANIFEST_PATH` I found there, but that didn't change anything.

What am I missing?

**Comment by hassanc** [comment]
I did the following before `flask run`

`npm install`
`npm run-script build`
`npm start`

It loads but just shows me a directory of files...

I used this issue as reference: #189 

https://github.com/sloria/cookiecutter-flask/issues/189

What else am I missing?

**Comment by chivalry** [comment]
I'll look into that, but I found a different Flask template that worked, which is what I was looking for. But I'll look into installing `npm` on my Mac and see if I can get it working.

**Comment by scollar71** [comment]
> I'll look into that, but I found a different Flask template that worked, which is what I was looking for. But I'll look into installing `npm` on my Mac and see if I can get it working.

Care to share which Boilerplate/Cookie cutter you're using? BTW This one has been a real time saver for me and Thank You to all the contributors!

**Comment by chivalry** [comment]
I went with RealPython's [cookiecutter-flask-skeleton](https://github.com/realpython/cookiecutter-flask-skeleton) and their instructions for [setup without Docker](https://github.com/realpython/cookiecutter-flask-skeleton/blob/master/%7B%7Bcookiecutter.app_slug%7D%7D/setup-without-docker.md).

I'm actually trying to learn the "proper" way to set up a Flask app with testing with the minimal amount of addons. Most of what RealPython's template uses I was already using (exceptions being `flake8`, `Flask-Bcrypt`, and `psycopg2`). You're not using much more than that. What I'm actually doing is using these templates as reference while I build from scratch something similar, piece by piece, so I understand why it's put together the way it is.

**Comment by Julien-Sytadelle** [comment]
I had the same provlme, I used a relative path : 
WEBPACK_MANIFEST_PATH = './webpack/manifest.json'

**Comment by oerd** [comment]
@chivalry the "generated" Flask project uses Webpack to _bundle_ static assets like javascript or css files. During development you should run the project via `npm start` command - it will run both Flask and webpack.

**Comment by nk9** [comment]
> I did the following before `flask run`
> 
> ```
> npm install
> npm run-script build
> flask db init
> flask db migrate
> flask db upgrade
> npm start
> ```

These were the steps I needed to get this template working. If they are essential, then I would suggest they be included in the README so that new users can understand how to get the app to actually run.

**Comment by jamescurtin** [comment]
Hi @nk9,

Below are the instructions included in the READMEs of all generated projects:

-----
Run the following commands to bootstrap your environment

```
git clone https://github.com/myuser/myproject
cd myproject
pip install -r requirements/dev.txt
cp .env.example .env
npm install
npm start  # run the webpack dev server and flask server using concurrently
```
You will see a pretty welcome screen.

Once you have installed your DBMS, run the following to create your app's database tables and perform the initial migration

```
flask db init
flask db migrate
flask db upgrade
npm start
```

-----

As an alternative you could use Docker (which also has a section in the generated project READMEs) which makes configuration even simpler:

```
docker-compose up flask-dev
```

Either of these two approaches should be sufficient to fully configure and bootstrap an application. 

I _think_ the confusion about how to bootstrap an application arises from the fact that many users expect usage info to be found in the main project's README. We prefer not to do this and instead keep usage-related information contained within the cookiecutter template, as the configuration instructions contain template fields that are only rendered after a project has been generated. I just updated the main README via https://github.com/cookiecutter-flask/cookiecutter-flask/pull/552 to clarify this.

If you feel as if additional clarification to the usage instructions would be valuable, please feel free to open a PR!

**Comment by nk9** [comment]
Thanks a ton for the super fast response. I came back having just seen these steps in the generated README, so yes, that's what caught me out. Your change is helpful! Can I also suggest a link from the main README into the github generated README? TBH, I often find myself skimming for a link or a code block when "I know what I'm looking for".
