### ISSUE TITLE
Using Vue with this setup

### ISSUE THREAD

**Issue by appnil** [cookiecutter-flask/cookiecutter-flask#482]
I am having trouble using Vue with this setup. I have installed Vue using npm but when I put the Vue code in **assets/js/script.js** it is not recognizing. Chrome console however prints that the Vue development is active **You are running Vue in development mode.**.

What am I doing wrong?

**Comment by jamescurtin** [comment]
HI @appnil, to better assist please provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and logs that show the issue you're having.

If I had to guess, you may want to add the Vue loader and configure a new rule in `webpack.config.js`

**Comment by jamescurtin** [comment]
Closing out due to lack of activity. Feel free to reopen if necessary!
