### ISSUE TITLE
Flask CLI uses wrong interpreter

### ISSUE THREAD

**Issue by mattdavis1121** [cookiecutter-flask/cookiecutter-flask#505]
Running the database setup commands per the README yields a `ModuleNotFoundError`:

```
$ flask db init
Traceback (most recent call last):
  File "/Users/matthewdavis/.virtualenvs/poker/bin/flask", line 6, in <module>
    from flask.cli import main
ModuleNotFoundError: No module named 'flask'
```

The file in the traceback has a shebang at the top, which I believe is overriding my virtualenv, forcing the script to use the wrong interpreter. 

```
#!/usr/local/Cellar/python/3.7.3/libexec/bin/python
# -*- coding: utf-8 -*-
import re
import sys

from flask.cli import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

Here's the correct interpreter.
```
$ which python
/Users/matthewdavis/.virtualenvs/poker/bin/python
```

If I replace the interpreter specified by the shebang with the one returned by `which python`, the script executes correctly. Obviously this isn't a good fix, as it means I have to edit module files.

Has anyone else run into this?

**Comment by jamescurtin** [comment]
Hi @mattdavis1121!

Could you provide more info about the file that has the `#!/usr/local/Cellar/python/3.7.3/libexec/bin/python` shebang? I don't believe that's generated by the cookiecutter.

Would using docker be feasible for your app? Given that this project has both Node & Python dependencies, I've found running the app in a container to be more straightforward.

Assuming you haven't customized your app too much yet, you should be able to get up and running via:

```bash
$ cp .env.example .env # the example .env has sensible defaults for running in dev
$ touch dev.db # this file is gitignored, so create it locally
$ docker-compose build
```
At that point:

```bash
$ docker-compose up flask-dev # confirm your app starts up in the browser
$ docker-compose run --rm manage db init
...
```

**Comment by mattdavis1121** [comment]
> Could you provide more info about the file that has the `#!/usr/local/Cellar/python/3.7.3/libexec/bin/python` shebang? I don't believe that's generated by the cookiecutter.

It's an executable installed by Flask. It's what gets invoked when the cli command `flask` is used -- i.e. `flask run` or `flask db init`.

**Comment by jamescurtin** [comment]
Gotcha--looks like this is a virtualenv/Flask issue. Some conversation about this problem can be found [here](https://github.com/pallets/flask/issues/2232). 

I'd try recreating the venv (that fixed the problem in the issue linked above) or switching to Docker. 

Thanks for using this project--please feel free to reach out if you run into any other issues!

**Comment by mattdavis1121** [comment]
@jamescurtin 

Yeah, I found that thread too. I dropped and recreated the virtual environment about ten times yesterday and it made no difference. This morning, fixed on the first try. No clue what that's about.

Thanks!
