### ISSUE TITLE
Github found security alert

### ISSUE THREAD

**Issue by ser** [cookiecutter-flask/cookiecutter-flask#526]
![Selection_131](https://user-images.githubusercontent.com/231537/61632314-be67a680-acb6-11e9-9f52-b876b9ee02c6.png)
![Selection_132](https://user-images.githubusercontent.com/231537/61632322-c32c5a80-acb6-11e9-9b78-80aecbab6dff.png)
![Selection_133](https://user-images.githubusercontent.com/231537/61632325-c6bfe180-acb6-11e9-996c-fc0b176d4a45.png)

**Comment by ser** [comment]
OK, I can see it is fixed in master. but the PIP version is not updated I am afraid and it is the source of the security alert.

**Comment by jamescurtin** [comment]
Sqlalchemy has been updated!
