### ISSUE TITLE
Docker image shouldn't run as root

### ISSUE THREAD

**Issue by itamarst** [cookiecutter-flask/cookiecutter-flask#528]
Running Docker images as root opens you to a variety of vulnerabilities, e.g. escalation to root-on-host CVE in February 2019 could be prevented by starting as non-root user.

For a detailed writeup see https://pythonspeed.com/articles/root-capabilities-docker-security/

I can submit a PR fixing this if you'd like.

**Comment by jamescurtin** [comment]
Thanks for raising! Please feel free to submit a PR-it would be appreciated.
