### ISSUE TITLE
Add non-docker running instructions to the readme file 

### ISSUE THREAD

**Issue by gregsifr** [cookiecutter-flask/cookiecutter-flask#529]
This is a go to template for flask however new webdev users (such as myself) may not know how to run the application outside of docker. 

Currently there are no non-docker instructions how to run the application, only ones which show how to install cookiecutter and initialize the template.

I cannot add these instructions as I am still figuring it out myself. What makes it different is understanding how JavaScript and npm fit into the picture and what needs to be run to deploy the application.

**Comment by jamescurtin** [comment]
Hi @gregsifr, thanks for the issue! The main project README only contains instructions for how to create a new project from the template. Once you have created a project from the template, check out the [generated README](https://github.com/cookiecutter-flask/cookiecutter-flask/tree/master/%7B%7Bcookiecutter.app_name%7D%7D), which contains the specific instructions you're looking for. (In this case, the [quickstart](https://github.com/cookiecutter-flask/cookiecutter-flask/tree/master/%7B%7Bcookiecutter.app_name%7D%7D#quickstart) instructions do not require Docker.)

**Comment by jamescurtin** [comment]
I've updated the main project's README with a [section](https://github.com/cookiecutter-flask/cookiecutter-flask#usage-instructions) that addresses this question. If you have any additional questions, don't hesitate to reach out!
