### ISSUE TITLE
exposing the flask app from docker to existing apache server

### ISSUE THREAD

**Issue by govindkelkar** [cookiecutter-flask/cookiecutter-flask#533]
The flask web-app need to be deployed to an public hosted web server where I can not bind the current docker image to port 80.
public url need to be without any port no.
Can we build docker image without web server in it and expose it to existing webserver for access?

**Comment by jamescurtin** [comment]
Hi @govindkelkar,

If I understand the question correctly, I believe you're asking about setting up a reverse proxy. That would allow for httpd to send traffic from your public URL (e.g. `https://myapp.example.com`) to your local app (e.g. `http://localhost:5000`). 

Does this post provide the information you need? https://stackoverflow.com/questions/54378292/interfacing-docker-containers-apps-with-an-existing-apache-web-server
