### ISSUE TITLE
Tests do not run on Travis due to the missing environmental variables.

### ISSUE THREAD

**Issue by TobKed** [cookiecutter-flask/cookiecutter-flask#553]
Tests do not run due to the missing `DATABASE_URL` and `SECRET_KEY` environmental variables. Exception is raised in `settings.py`. I think it is good idea to require these variables for prod/dev environment so the user will be aware what database is used.
I've created PR which fix this issue: 
https://github.com/cookiecutter-flask/cookiecutter-flask/pull/551

**Comment by jamescurtin** [comment]
Thanks for the issue! Just updated the PR with a suggestion

**Comment by jamescurtin** [comment]
Closed by #551
