### ISSUE TITLE
windows compatibility

### ISSUE THREAD

**Issue by kg-2** [cookiecutter-flask/cookiecutter-flask#566]
This is related to #244- This command is needed to correctly set the environmental variables without changing the scripts on windows:
`npm install -g win-node-env`
Adding it to the readme would be helpful for new users.

Also, I think .env.example is supposed to be a directory, but on windows its a file.

**Comment by TobKed** [comment]
`.env.example` it is and should be a file

**Comment by jamescurtin** [comment]
Hi @kg-2, instead of asking users to install `win-node-env` globally via the README, I think it would be better to add it as a dependency in `package.json`. Would you be willing to put in a PR? I am not on Windows & this project's CI runs on linux, so I'd be unable to test directly without some finagling.

To your second comment, as TobKed mentioned, `.env.example` should be a file. The application sets environment variables from a file called `.env`. That file is gitignored to prevent people from accidentally committing secret variables. In order to show which environment variables are required, we provide the file `.env.example`. As per the instructions, you can make a copy of `.env.example` and rename to `.env` for testing purposes.

**Comment by kg-2** [comment]
A PR shouldn't be a problem. This is my first adventure with cookiecutter so it will take some poking around. After renaming the .env file it's closer to running, but now I get a 

> Cannot find module ../../client/

webpack error. The flask-debug toolbar extension seems to be working, but the rest of the site is basic html. Firefox's console reports

> Loading failed for the <script> with source “http://0.0.0.0:2992/static/build/main_js.36bdf1dbd4326dbfea4c.js”

Firefox debugger:

> Error loading this URI: Protocol error (unknownError): Could not load the source for blob:http://localhost:5000/1ce8533f-9773-41cc-b3e8-9f386c0c7c8b.
> [Exception... "Failed to open input source 'blob:http://localhost:5000/1ce8533f-9773-41cc-b3e8-9f386c0c7c8b'"  nsresult: "0x805303f4 (<unknown>)"  location: "JS frame :: resource://devtools/shared/DevToolsUtils.js :: mainThreadFetch/< :: line 666"  data: yes]
> Stack: mainThreadFetch/<@resource://devtools/shared/DevToolsUtils.js:666:15
> mainThreadFetch@resource://devtools/shared/DevToolsUtils.js:531:10
> _getSourceText@resource://devtools/server/actors/source.js:299:27
> Line: 666, column: 0

Windows command prompt output:

> Microsoft Windows [Version 10.0.18362.10019]
> (c) 2019 Microsoft Corporation. All rights reserved.
> 
> (bwa-ZEorA9d-) C:\Users\kevin\python\projects\bwa>npm start
> 
> > bwa@1.0.0 start C:\Users\kevin\python\projects\bwa
> > concurrently -n "WEBPACK,FLASK" -c "bgBlue.bold,bgMagenta.bold" "npm run webpack-dev-server" "npm run flask-server"
> 
> [WEBPACK]
> [WEBPACK] > bwa@1.0.0 webpack-dev-server C:\Users\kevin\python\projects\bwa
> [WEBPACK] > NODE_ENV=debug webpack-dev-server --host=0.0.0.0 --port 2992 --hot --inline
> [WEBPACK]
> [FLASK]
> [FLASK] > bwa@1.0.0 flask-server C:\Users\kevin\python\projects\bwa
> [FLASK] > pipenv run flask run --host=0.0.0.0
> [FLASK]
> [FLASK] Loading .env environment variables�
> [WEBPACK] Error: Cannot find module '../../client/'
> [WEBPACK] Require stack:
> [WEBPACK] - C:\Users\kevin\python\projects\bwa\node_modules\webpack-dev-server\lib\utils\addEntries.js
> [WEBPACK] - C:\Users\kevin\python\projects\bwa\node_modules\webpack-dev-server\lib\utils\updateCompiler.js
> [WEBPACK] - C:\Users\kevin\python\projects\bwa\node_modules\webpack-dev-server\lib\Server.js
> [WEBPACK] - C:\Users\kevin\python\projects\bwa\node_modules\webpack-dev-server\bin\webpack-dev-server.js
> [WEBPACK]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
> [WEBPACK]     at Function.resolve (internal/modules/cjs/helpers.js:80:19)
> [WEBPACK]     at addEntries (C:\Users\kevin\python\projects\bwa\node_modules\webpack-dev-server\lib\utils\addEntries.js:39:36)
> [WEBPACK]     at updateCompiler (C:\Users\kevin\python\projects\bwa\node_modules\webpack-dev-server\lib\utils\updateCompiler.js:48:5)
> [WEBPACK]     at new Server (C:\Users\kevin\python\projects\bwa\node_modules\webpack-dev-server\lib\Server.js:72:5)
> [WEBPACK]     at startDevServer (C:\Users\kevin\python\projects\bwa\node_modules\webpack-dev-server\bin\webpack-dev-server.js:106:14)
> [WEBPACK]     at C:\Users\kevin\python\projects\bwa\node_modules\webpack-dev-server\bin\webpack-dev-server.js:166:3
> [WEBPACK]     at C:\Users\kevin\python\projects\bwa\node_modules\webpack-dev-server\lib\utils\processOptions.js:33:9
> [WEBPACK] Note: This command was run via npm module 'win-node-env'
> [WEBPACK] npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> [WEBPACK] npm ERR! bwa@1.0.0 webpack-dev-server: `NODE_ENV=debug webpack-dev-server --host=0.0.0.0 --port 2992 --hot --inline`
> npm ERR! Exit status 1
> npm ERR!
> [WEBPACK] npm ERR! Failed at the bwa@1.0.0 webpack-dev-server script.
> [WEBPACK] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [WEBPACK]
> [WEBPACK] npm ERR! A complete log of this run can be found in:
> [WEBPACK] npm ERR!     C:\Users\kevin\AppData\Roaming\npm-cache\_logs\2019-09-26T14_56_12_815Z-debug.log
> [WEBPACK] npm run webpack-dev-server exited with code 1
> [FLASK]  * Serving Flask app "autoapp.py" (lazy loading)
> [FLASK]  * Environment: development
> [FLASK]  * Debug mode: on
> [FLASK]  * Restarting with stat
> [FLASK]  * Debugger is active!
> [FLASK]  * Debugger PIN: 314-457-074
> [FLASK]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
> [FLASK] [2019-09-26 07:59:52,556] INFO in views: Hello from the home page!
> [FLASK] 127.0.0.1 - - [26/Sep/2019 07:59:53] "GET / HTTP/1.1" 200 -
> [FLASK] 127.0.0.1 - - [26/Sep/2019 07:59:54] "GET /_debug_toolbar/static/js/jquery.js HTTP/1.1" 200 -
> [FLASK] 127.0.0.1 - - [26/Sep/2019 07:59:54] "GET /_debug_toolbar/static/js/toolbar.js HTTP/1.1" 200 -
> [FLASK] 127.0.0.1 - - [26/Sep/2019 07:59:54] "GET /_debug_toolbar/static/js/jquery.tablesorter.js HTTP/1.1" 200 -
> [FLASK] 127.0.0.1 - - [26/Sep/2019 07:59:54] "GET /_debug_toolbar/static/css/toolbar.css?0.06800776835159794 HTTP/1.1" 200 -
> [FLASK] 127.0.0.1 - - [26/Sep/2019 07:59:54] "GET /favicon.ico HTTP/1.1" 404 -
> [FLASK] 127.0.0.1 - - [26/Sep/2019 07:59:54] "GET /_debug_toolbar/static/img/tick-red.png HTTP/1.1" 200 -
> [FLASK] 127.0.0.1 - - [26/Sep/2019 08:00:04] "GET /_debug_toolbar/static/img/indicator.png HTTP/1.1" 200 -
> [FLASK] 127.0.0.1 - - [26/Sep/2019 08:00:04] "GET /_debug_toolbar/static/img/close.png HTTP/1.1" 200 -
> [FLASK] 127.0.0.1 - - [26/Sep/2019 08:00:12] "GET /_debug_toolbar/static/img/close_hover.png HTTP/1.1" 200 -

**Comment by psdon** [comment]
This issue can now be closed as the latest released version don't use webpack-dev-server anymore.
