### ISSUE TITLE
flask not serving bootstrap/css/js

### ISSUE THREAD

**Issue by kg-2** [cookiecutter-flask/cookiecutter-flask#567]
Running on windows 10, python 3.6, with or without pipenv

running the command `npm start`  starts flask and webpack without any errors
It reports that webpack is running on http://0.0.0.0:2992/ and flask is running on http://0.0.0.0:5000/. When I navigate to `localhost:5000` I get the same basic html page as is pictured in #409 as if I ran `flask run` instead of `npm start`. When I navigate to `localhost:2992` I get a file/directory explorer page. 

There are no errors reported in the cmd prompt nor the console. Any ideas? Thanks

**Comment by jamescurtin** [comment]
When you say console, do you mean your web browser's console? I wonder if this is related to your other issue with setting environment variables. Do you have docker installed? It would be great if you were able to start up the app in Docker (`docker-compose up flask-dev`); that would help triangulate if this is problem is related to your windows-specific setup, or if something else is wrong.

**Comment by maks232** [comment]
I was facing the same issue. Following this [post](https://superuser.com/questions/536156/how-do-i-get-0-0-0-0-to-resolve-to-localhost-when-browsing-a-url-that-contains-0) I changed all -host addresses from 0.0.0.0 to 127.0.0.1 in the package.json file.

It works fine for local development

**Comment by mg41** [comment]
To fix for production sans docker, seems like exporting FLASK_ENV=production and then calling npm run build works, by triggering the production NODE_ENV environment for compilation.
