### ISSUE TITLE
flask template changed does not auto-reload

### ISSUE THREAD

**Issue by psdon** [cookiecutter-flask/cookiecutter-flask#594]
When I change something in template, it does not auto reload even I set `app.config['TEMPLATES_AUTO_RELOAD'] = True`

**Comment by psdon** [comment]
I found a work around how to auto reload the Flask app when it detects some changes in the templates directory, but it does not auto reload the browser and looks like Flask does not support it natively. 

Do you guys think autoreloading feature is a good feature to add to this cookiecutter template? I'm willing to make a pull request.

**Comment by jamescurtin** [comment]
Based on the [Flask docs](https://flask.palletsprojects.com/en/1.1.x/config/#TEMPLATES_AUTO_RELOAD), `TEMPLATES_AUTO_RELOAD` is enabled by default when the app is launched in debug mode, so we shouldn't need to set anything manually.

Could you clarify what the nature of your PR would be (_i.e._ do you mean a workaround that would cause the browser to auto-reload when a change is detected)? In general, I would prefer not to add something like this--but it is definitely worth it to include a link to the approach you're using for any other developers who may be looking at the issues in this project!
