### ISSUE TITLE
context-processor

### ISSUE THREAD

**Issue by govindkelkar** [cookiecutter-flask/cookiecutter-flask#598]
How to access @app in cookiecutter?
I want to insert variables in it so that they can be accessed in jinja2 template.

**Comment by jamescurtin** [comment]
One approach: Create a new module that contains your desired context processor functions.

```tree
my_flask_app
├── __init__.py
├── app.py
├── context_processors.py  # New Module
├── ...
```

```python
# context_processors.py
def inject_foo():
    return {"foo": "Foo"}


def inject_bar():
    return {"bar": "Bar"}
```

Then modify `app.py` to include a new function that configures all context processors (it will be called within `create_app`).

```python
# app.py

...

from my_flask_app.context_processors import inject_bar, inject_foo

def create_app(config_object="my_flask_app.settings"):
    app = Flask(__name__.split(".")[0])
    app.config.from_object(config_object)
    register_extensions(app)
    ...
    configure_context_processors(app)
    return app

...

def configure_context_processors(app):
    processors = [inject_foo, inject_bar]
    for processor in processors:
        app.context_processor(processor)
```

At this point, you will be able to include `{{ foo }}` or `{{ bar }}` in any template, and the corresponding values "Foo" and "Bar" will be templated in.

**Comment by govindkelkar** [comment]
jamescurtin thanks for the reply and sorry for delay from my side. This piece of code should have been documented somewhere in the documentation as it is very necessary to access "app" context.
Thank you once again.
