### ISSUE TITLE
Any guide how to properly implement compression-webpack-plugin

### ISSUE THREAD

**Issue by psdon** [cookiecutter-flask/cookiecutter-flask#599]
I would like to compressed the assets to a gzip files, but I'm struggling how to properly implement this with the `manifest-revision-plugin`. `manifest-revision-plugin` does not generate the correct mappings for .gz  files, instead it mapped the uncompressed files.

This is how I tried implementing this:
```
const CompressionPlugin = require('compression-webpack-plugin');

new CompressionPlugin({
          filename: '[path].gz[query]',
          algorithm: 'gzip',
          test: /\.js$|\.css$|\.html$|\.eot?.+$|\.ttf?.+$|\.woff?.+$/,
          threshold: 0,
          minRatio: 0.8,
          deleteOriginalAssets: true,
    }),
    new ManifestRevisionPlugin(path.join(__dirname, 'app', 'webpack', 'manifest.json'), {
      rootAssetPath,
      ignorePaths: ['/js', '/css'],
      extensionsRegex: /\.(ttf|eot|svg|png|jpe?g|gif|ico)$/i,
    }),
``

**Comment by jamescurtin** [comment]
Will close this out for now, as the issue you created on the plugin (https://github.com/nickjj/manifest-revision-webpack-plugin/issues/53) seems like a better place for this discussion. But please feel free to follow up here with findings!
