### ISSUE TITLE
Deprecated Flask-Webpack

### ISSUE THREAD

**Issue by MrBlaise** [cookiecutter-flask/cookiecutter-flask#605]
The Flask-Webpack library was deprecated in favour of https://github.com/nickjj/flask-static-digest.

I am having hard time migrating to it, I have opened an issue about it: https://github.com/nickjj/flask-static-digest/issues/1

Could you update the template?

**Comment by nickjj** [comment]
I never heard of or used this cookie cutter project but the general migration path would be:

#### Dependency changes

1. Remove Flask-Webpack from `requirements.txt`
2. Remove `manifest-revision-webpack-plugin` from `package.json`
3. Add `Flask-Static-Digest` to `requirements.txt`

#### Jinja 2 template changes

1. Replace `stylesheet_tag('main_css') | safe` with `static_url_for('static', filename='css/main.css')`
2. Replace `javascript_tag('main_css') | safe` with `static_url_for('static', filename='js/main.js')`
3. Replace any instances of `asset_url_for('foo.png')` with `static_url_for('static', filename='images/foo.png')`

All of the details about Flask-Static-Digest can be found at: https://github.com/nickjj/flask-static-digest

**Comment by jamescurtin** [comment]
Thanks for raising the issue @MrBlaise and big thanks to @nickjj for very kindly providing such detailed information! Nick—is this something you’d like to take on and make a PR for (new contributors always welcome!)? Otherwise, I will make this fix in the next week or two.

**Comment by nickjj** [comment]
Thanks for including it into this project @jamescurtin, and good call about removing the old references to flask-webpack in your Flask config. I forgot to add that to the migration guide.
