### ISSUE TITLE
Support Conditional Requirements

### ISSUE THREAD

**Issue by jamescurtin** [cookiecutter-flask/cookiecutter-flask#608]
Some packages are only relevant to certain users, based on the selected options during project generation. We cannot currently use jinja templating in requirements files, however, because this causes dependabot parsing to fail.

We need to implement some functionality that would allow for unnecessary dependencies to be removed from requirements files during template generation.

**Comment by TobKed** [comment]
I was thinking about this but I am concerned about keeping dependencies  in two places. The logic would be little bit hidden and harder to understand. `if/else` statement in `requirements.txt` is more explicit. I've started making research on this topic and I see **cookiecutter-django** uses https://github.com/pyupio/pyup.
Here is example of PR with updated requirements file with jinja expressions: https://github.com/pydanny/cookiecutter-django/pull/2278.
WDYT about **pyup**?

**Comment by jamescurtin** [comment]
Hi @TobKed! Sorry for delayed response. My preference would be to keep Dependabot instead of moving to pyup, especially now that Dependabot is now a Github project. To that end, I've submitted a PR to the dependbot repo (https://github.com/dependabot/dependabot-core/pull/1537) to add support for Jinja templates in requirements files.

Assuming the enhancement is approved, I think we would be ready to merge https://github.com/cookiecutter-flask/cookiecutter-flask/pull/607!

**Comment by jamescurtin** [comment]
This is now resolved (see https://github.com/cookiecutter-flask/cookiecutter-flask/pull/645 for a test of this)

**Comment by TobKed** [comment]
Great @jamescurtin ! Good job!
