### ISSUE TITLE
Stopping generation because pre_gen_project hook script didn't exit successfully

### ISSUE THREAD

**Issue by ashwin47** [cookiecutter-flask/cookiecutter-flask#616]
`  File "/tmp/tmpoJStZp.py", line 17
    return f"{code}{text}{bcolors.ENDC}"
                                       ^
SyntaxError: invalid syntax
ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)`

Looks like it broke recently. Made it work by checking out to a week old version.

**Comment by sergioisidoro** [comment]
Also got the same issue.
```
Select use_pipenv:
1 - no
2 - yes
Choose from 1, 2 [1]: 2
Select python_version:
1 - 3.8
2 - 3.7
3 - 3.6
Choose from 1, 2, 3 [1]: 2
Select node_version:
1 - 12
2 - 10
Choose from 1, 2 [1]: 1
Select use_heroku:
1 - no
2 - yes
Choose from 1, 2 [1]: 1
  File "/var/folders/yk/zk1ws3wj6033f6mvq1m3y4bm0000gn/T/tmppxWt7N.py", line 17
    return f"{code}{text}{bcolors.ENDC}"
                                       ^
SyntaxError: invalid syntax
```

**Comment by sergioisidoro** [comment]
It seems that https://github.com/cookiecutter-flask/cookiecutter-flask/pull/606 was merged without tests passing...

**Comment by jamescurtin** [comment]
Can you confirm which version of Python you are using? This functionality uses f-strings, which were introduced in Python 3.6; my guess is that users encountering this error are either on python 2.7 or an older version of Python 3.

Given that the cookiecutter template only supports generating new projects in versions `3.6`, `3.7`, or `3.8`, I am comfortable removing backwards compatibility for Python versions < 3.6. 

Let me add some documentation to clarify this in the project README; will close out this issue once that has been done.

**Comment by sergioisidoro** [comment]
I have an alias of python to python3 (3.7), but it's on my shell rc (osx). 
I guess cookiecutter picks up python from the path instead?

But yes, it seems that this was the first breaking change to python 2.7, so it's nice if there would be a clear readme warning :)

**Comment by sergioisidoro** [comment]
Seems to be working with virtualenv. The solution of aliasing python to python3 binary on MacOS seems not to be very reliable with cookiecutter

Leaving this here for people looking for a **quick solution** with virtualenv

```.sh
## After installing python 3
unalias python # if you have python aliased to python3 
virtualenv -p python3 venv   
source venv/bin/activate 
## Run cookiecutter
deactivate # or not :)

```
