### ISSUE TITLE
Images in Assets folder doesn't get into /static/ files

### ISSUE THREAD

**Issue by psdon** [cookiecutter-flask/cookiecutter-flask#621]
Migrating to Flask-Static-Digest.

### Reproduce
- Insert an image to /assets/img/
- `npm start`
- Check `/app/static/build/` folder and you can't find the image you put in the assets folder

**Comment by psdon** [comment]
### Update
It turns out I have to put images and svg directly to /static/ directory. Webpack `file-loader` can't detect those files, as it needs to be _`imported`_ in a JS file, where consequently the `manifest-revision-webpack-plugin` does that for you. Removing it and migrating to Flask-Static-Digest broke it.

**Comment by jamescurtin** [comment]
Hi @psdon -- images shouldn't be put directly into the `/static` directory. The solution here is to add logic to `main.js` that will auto-include all files in a given directory. For example:

```javascript
// main.js

...

require.context(
    "../img", // context folder
    true, // include subdirectories
    /.*/ // RegExp
)
```

This will force all files in the `/assets/img` directory to be automatically loaded. I'm putting in a PR to resolve this (and also add a favicon to demonstrate that it works)
