### ISSUE TITLE
Problem with Flask-Static-Digest as a Webpack heavy user.

### ISSUE THREAD

**Issue by psdon** [cookiecutter-flask/cookiecutter-flask#630]
Recently Mr. Nick, the author of `Flask-Webpack` officially declared that the Flask extension will no longer be supported, and he created a new plugin called `Flask-Static-Digest` as a replacement. The plugin is awesome for md5 hashing and compression, it's good for someone who doesn't use Webpack. I was excited at first, but as the migration goes I crossed into a dilemma. 

### Problem
1. I **cannot separate** the **Webpack build server**, and the **Flask server**. I'm running a big website which we are adding images (i.e. for blogs) and other static assets in a daily basis. The problem here is I have to host my `static files` inside the Flask server as the md5 hashing function is dependent to the flask extension. It's a good practice separating the static server, specially for big websites.

2. I have to **restart** the Flask server in every Webpack build. When I run `flask digest compile`, it creates a `cache_manifest.json` file. And it only reads the JSON file when the Flask server started. 

3. This is a minor problem, but I'm used to JS dynamic import a lot and by using `flask-static-digest`, the dynamically imported JS file doesn't grab the `md5` hashed version. Webpack creates a mapping on which file it gets loaded. The problem is md5 hashing doesn't happen inside Webpack, so the generated mappings will only mapped the original files, and the hashed files is kinda useless.

### Solution
I used this awesome Flask cookiecutter template all over my projects, and its a good idea to solve this problem within the repo than creating a fork for myself. And it would help the community which they might encounter the same problem I had.

I have created a new Flask extension that addressed all Webpack management problem I've experienced. You can check this repository -> https://github.com/psdon/Flask-Manage-Webpack

1. `Flask-Manage-Webpack` made it possible to separate your Webpack build server and Flask server.
2. You don't have to restart the Flask server in every build. Check `In Production` section to know how-to. 
3. Using dynamic import is not a pain anymore.
4. As a bonus point, beginners don't have to create a new Webpack config file for themselves. I have created a Webpack config template to bootstrap their environment fast. (For those who don't use this cookiecutter template)

**Comment by jamescurtin** [comment]
Hi, @psdon: 

I've shared this on the `Flask-Static-Digest` project to get feedback from nickjj. If he thinks some of these issues can be solved with the existing plugin, I'd prefer to stick with what we already have.

**Comment by jamescurtin** [comment]
Thanks for submitting this issue; based on the discussion in the other issue linked above, I'm going to close this out. The use case your new package solves for is very specialized, and sounds like it works well for you--but not necessarily the right option for the average Flask user.
