### ISSUE TITLE
Error: unable to open database file

### ISSUE THREAD

**Issue by justinmoon** [cookiecutter-flask/cookiecutter-flask#633]
I did the following:

```
git clone git@github.com:cookiecutter-flask/cookiecutter-flask.git
/cookiecutter-docker.sh
...
cd app
docker-compose up flask-dev
```

I opened up the site at localhost:5000 and filled out the registration form. Upon submitting it I got the following error:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/e3q8)
```

There was a `dev.db/` folder in the `app` directory owned by root. This seemed strange ...

I'm on Manjaro (Arch) Linux.
Docker version: Docker version 19.03.4-ce, build 9013bf583a
Docker-compose version: docker-compose version 1.24.1, build unknown

**Comment by justinmoon** [comment]
Seem I just forgot to run the database creation commands:

```
docker-compose run --rm manage db init
docker-compose run --rm manage db migrate
docker-compose run --rm manage db upgrade
```

**Comment by yurivanmidden** [comment]
> There was a `dev.db/` folder in the `app` directory owned by root. This seemed strange ...

True, docker-compose does that when you run `docker-compose [ up | run ]`, as it tries to mount that directory in the container. Run `touch dev.db` before running the containers to create a dev.db file instead of a directory.

**Comment by ZackWhiteIT** [comment]
Hi, I ran into a similar problem, but touching dev.db didn't solve the problem for me. Identical stack trace. *shrugs*

**Comment by jamescurtin** [comment]
> Hi, I ran into a similar problem, but touching dev.db didn't solve the problem for me. Identical stack trace. _shrugs_

Late response, but one clarification: If a directory named `dev.db` already exists, `touch`ing it won't have any effect. If you've already run into this issue, you need to delete the directory before running `touch dev.db` (which ensures it exists as a file, not a directory).

**Comment by foxale** [comment]
Same here, wasted hours before realized

**Comment by stodge** [comment]
I ran:

```
docker-compose up flask-dev
docker-compose run --rm manage db init
docker-compose run --rm manage db migrate
```

on a fresh project and I get this error too:

```
docker-compose run --rm manage db migrate
sqlite3.OperationalError: unable to open database file
ls -al /tmp/dev.db
total 8
drwxr-xr-x 2 root root 4096 May  4 13:57 .
drwxrwxrwt 1 root root 4096 May  4 13:57 ..
```
I'll look at the code and see if I can fix it, but I'm no docker expert.

Thanks for pointing out the fix.
