### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by gmoorevt** [cookiecutter-flask/cookiecutter-flask#642]
I am getting the following error:

`Choose from 1, 2 [1]: 1
  File "/var/folders/rj/q7hdh2dn033cxsz7z3y1v8d00000gp/T/tmpKMwPvf.py", line 17
    return f"{code}{text}{bcolors.ENDC}"
                                       ^
SyntaxError: invalid syntax
ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
`

**Comment by jamescurtin** [comment]
Hi @gmoorevt, when running this project locally, you'll need to have a version of Python >= 3.6. This error suggests you are using an older version of Python.

The alternative approach (if you do not want to upgrade Python) would be to use Docker. If Docker is installed on your local machine, all you need to do is run `./cookiecutter-docker.sh`. The generated project can also be run inside of a container, which eliminates a lot of incompatibilities like this.

**Comment by jamescurtin** [comment]
Based on the most recent PR, you will receive a more user-friendly error message if the cookiecutter is run from an incompatible Python version!

e.g.

```basg=h
$ python2 -m cookiecutter .
  ...
  Choose from 1, 2 (1, 2): 1
  WARNING: You are running cookiecutter using Python 2.7, but a version >= Python 3.6+ is required.
  Either install a more recent version of Python, or use the Docker instructions.

**Comment by gmoorevt** [comment]
Thanks so much. My error.  Just got a new laptop and didn’t realize my config was messed up.
