### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by dferraro303** [cookiecutter-flask/cookiecutter-flask#648]
I have not been successful in running this using docker or the standard method.

When attempting to run using the docker method I get the error
Hook script failed (error: [Errno 2] No such file or directory: '/build/myproject')

When attempting to run using the standard method on a windows 10 machine I get:
ModuleNotFoundError: No module named 'hooks'

**Comment by jamescurtin** [comment]
The issue you're seeing with the standard method was just addressed by https://github.com/cookiecutter-flask/cookiecutter-flask/pull/644. It should work now...but please comment if it doesn't. 🙂 

As for the docker version, my guess is that it has to do with [this line](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/993b7d16c6764e9da9a758f6295c9ff777f04092/cookiecutter-docker.sh#L60) where the environment variable `PWD` is being used to mount the current working directory to the docker container. That environment variable isn't available in Windows command prompt, but I _think_ it is available in Powershell and I'm almost positive it is available in *nix emulators like git bash.

Would you be able to try running the docker version using one of those programs and let me know if you're still seeing the issue? If that resolves it, I will add in Windows-specific documentation to address this.

**Comment by dferraro303** [comment]
Thanks, The hooks ModuleNotFoundError is fixed. 

When following the readme.md and getting the npm start I got the error: 'NODE_ENV' is not recognized so I added SET to the package.json webpack-watch 'SET NODE_ENV=debug   

After this change, I received no more errors. However, when I opened the site the css and js bundle could not be found. Looks like the files were not created, the static/build did not have them. I tried to manually create this with npm webpack which I'm not sure was the correct thing to do. I got the error configuration.mode should be one of these: "development" | "production" | "none". Is there something else I should try?

As for Docker. I attempted this on an Ubuntu 16.04 box that I have several other containers running. The steps I used: 
sudo bash
git clone https://github.com/cookiecutter-flask/cookiecutter-flask.git
cd cookiecutter-flask
./cookiecutter-docker.sh
I selected all the defaults and got the No such file or directory: '/build/my_app

Thanks for the help.

**Comment by pgierz** [comment]
I also have the same problem...

**Comment by markman123** [comment]
This is running on windows, where env variables need the SET command (as you've correctly pointed out). 

Try changing this section of `package.json`, noting the `&&` after setting the env variable:

```js
"scripts": {
    "build": "SET NODE_ENV=production && webpack --progress --colors -p && npm run flask-static-digest",
    "start": "concurrently -n \"WEBPACK,FLASK\" -c \"bgBlue.bold,bgMagenta.bold\" \"npm run webpack-watch\" \"npm run flask-server\"",
    "webpack-watch": "SET NODE_ENV=debug && webpack --mode development --watch",
    "flask-server": "pipenv run flask run --host=0.0.0.0",
    "flask-static-digest": "pipenv run flask digest compile",
    "lint": "eslint \"assets/js/*.js\""
  }
```
