### ISSUE TITLE
Could not find app.py

### ISSUE THREAD

**Issue by gardiac2002** [cookiecutter-flask/cookiecutter-flask#651]
I followed the instructions for creating a cookiecutter project with `docker-compose`
but when I start docker-compose I receive the following error and the project does not
start:

`flask-dev_1   | [FLASK]`

`flask-dev_1   | [FLASK] Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.`

`flask-dev_1   | [FLASK] npm ERR! code ELIFECYCLE`

`flask-dev_1   | [FLASK] npm ERR! errno 2`

`flask-dev_1   | [FLASK] npm ERR! project@1.0.0 flask-server: `flask run --host=0.0.0.0``

`flask-dev_1   | [FLASK] npm ERR! Exit status 2`
`flask-dev_1   | [FLASK] npm ERR! `

Do I need some additional configuration?

**Comment by gardiac2002** [comment]
Is it correct that I change the docker-compose.yml?
```
    environment:
      FLASK_APP: my_project/app.py
```

**Comment by gardiac2002** [comment]
Ok, sorry guys. I just realized that I should have just added the `.env` file.

**Comment by jamescurtin** [comment]
No worries! Closing out
