### ISSUE TITLE
(non-Docker) .env file parsing SEND_FILE_MAX_AGE_DEFAULT fails due to comment

### ISSUE THREAD

**Issue by mbennett-uoe** [cookiecutter-flask/cookiecutter-flask#660]
When using the non-Docker version of this cookiecutter, the initial "npm start" inside the pipenv brings up the server, but no pages will load as the .env file fails to parse properly. i don't know if this also affects the Dockerised version.

The error message is `environs.EnvValidationError: Environment variable "SEND_FILE_MAX_AGE_DEFAULT" invalid: Not a valid integer.`

Using the interactive debugger shows that this is because the environs library is attempting to parse the whole line from the .env file, without omitting the comment. This causes the integer parse to fail, obviously!

![cookiecutter error2](https://user-images.githubusercontent.com/29146501/71194286-91c6b380-2283-11ea-8a90-bd4f7c8e8114.png)

Simplest quick fix would be to move the comment to the line above, so I'll fire in a PR to do this shortly, but longer term probably a bug needs to be registered against the environs library.

**Comment by mbennett-uoe** [comment]
Here's the full stacktrace:

`[FLASK] 129.215.240.173 - - [19/Dec/2019 17:12:04] "GET / HTTP/1.1" 500 -
[FLASK] Traceback (most recent call last):
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 901, in _validated
[FLASK]     return self._format_num(value)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 891, in _format_num
[FLASK]     return self.num_type(value)
[FLASK] ValueError: invalid literal for int() with base 10: '10 # In production, set to a higher number, like 31556926'
[FLASK] 
[FLASK] The above exception was the direct cause of the following exception:
[FLASK] 
[FLASK] Traceback (most recent call last):
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/environs/__init__.py", line 84, in method
[FLASK]     value = field.deserialize(value)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 351, in deserialize
[FLASK]     output = self._deserialize(value, attr, data, **kwargs)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 920, in _deserialize
[FLASK]     return self._validated(value)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 946, in _validated
[FLASK]     return super()._validated(value)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 903, in _validated
[FLASK]     raise self.make_error("invalid", input=value) from error
[FLASK] marshmallow.exceptions.ValidationError: Not a valid integer.
[FLASK] 
[FLASK] The above exception was the direct cause of the following exception:
[FLASK] 
[FLASK] Traceback (most recent call last):
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
[FLASK]     raise value
[FLASK]   File "/home/ubuntu/bre_card_catalogue/autoapp.py", line 5, in <module>
[FLASK]     app = create_app()
[FLASK]   File "/home/ubuntu/bre_card_catalogue/bre_card_catalogue/app.py", line 27, in create_app
[FLASK]     app.config.from_object(config_object)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/flask/config.py", line 174, in from_object
[FLASK]     obj = import_string(obj)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/werkzeug/utils.py", line 546, in import_string
[FLASK]     __import__(import_name)
[FLASK]   File "/home/ubuntu/bre_card_catalogue/bre_card_catalogue/settings.py", line 18, in <module>
[FLASK]     SEND_FILE_MAX_AGE_DEFAULT = env.int("SEND_FILE_MAX_AGE_DEFAULT")
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/environs/__init__.py", line 89, in method
[FLASK]     ) from error
[FLASK] environs.EnvValidationError: Environment variable "SEND_FILE_MAX_AGE_DEFAULT" invalid: Not a valid integer.
`

**Comment by mbennett-uoe** [comment]
Here's the full stacktrace:

`[FLASK]` 129.215.240.173 - - [19/Dec/2019 17:12:04] "GET / HTTP/1.1" 500 -
[FLASK] Traceback (most recent call last):
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 901, in _validated
[FLASK]     return self._format_num(value)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 891, in _format_num
[FLASK]     return self.num_type(value)
[FLASK] ValueError: invalid literal for int() with base 10: '10 # In production, set to a higher number, like 31556926'
[FLASK] 
[FLASK] The above exception was the direct cause of the following exception:
[FLASK] 
[FLASK] Traceback (most recent call last):
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/environs/__init__.py", line 84, in method
[FLASK]     value = field.deserialize(value)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 351, in deserialize
[FLASK]     output = self._deserialize(value, attr, data, **kwargs)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 920, in _deserialize
[FLASK]     return self._validated(value)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 946, in _validated
[FLASK]     return super()._validated(value)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 903, in _validated
[FLASK]     raise self.make_error("invalid", input=value) from error
[FLASK] marshmallow.exceptions.ValidationError: Not a valid integer.
[FLASK] 
[FLASK] The above exception was the direct cause of the following exception:
[FLASK] 
[FLASK] Traceback (most recent call last):
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
[FLASK]     raise value
[FLASK]   File "/home/ubuntu/bre_card_catalogue/autoapp.py", line 5, in <module>
[FLASK]     app = create_app()
[FLASK]   File "/home/ubuntu/bre_card_catalogue/bre_card_catalogue/app.py", line 27, in create_app
[FLASK]     app.config.from_object(config_object)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/flask/config.py", line 174, in from_object
[FLASK]     obj = import_string(obj)
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/werkzeug/utils.py", line 546, in import_string
[FLASK]     __import__(import_name)
[FLASK]   File "/home/ubuntu/bre_card_catalogue/bre_card_catalogue/settings.py", line 18, in <module>
[FLASK]     SEND_FILE_MAX_AGE_DEFAULT = env.int("SEND_FILE_MAX_AGE_DEFAULT")
[FLASK]   File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/environs/__init__.py", line 89, in method
[FLASK]     ) from error
[FLASK] environs.EnvValidationError: Environment variable "SEND_FILE_MAX_AGE_DEFAULT" invalid: Not a valid integer.`

**Comment by jamescurtin** [comment]
This is interesting--I am unable to reproduce this error when creating a fresh project, using either the docker or non-docker approach. 

Could you provide the version of `environs` you are on? May also be worth sanity checking with a fresh copy of `.env` (e.g. backing up your current `.env` and running a `cp .env.example .env`) Below is a minimal reproducible example where `environs` is able to correctly parse variables of different types, even with a comment.

```python
from tempfile import NamedTemporaryFile

import pytest
from environs import Env, EnvValidationError # environs==7.1.0

with NamedTemporaryFile() as temp:
    temp.write(b"A=foo\n")
    temp.write(b"B=123 # with a comment\n")
    env = Env()
    env.read_env(temp.name)


with pytest.raises(EnvValidationError):
    assert env.int("A")  # Expected to fail
    
assert env.int("B") == 123
```

**Comment by mbennett-uoe** [comment]
I'll fish out the environs details when I get to the office, but this was a brand new cookiecutter using pipenv, so I can't see any reason why it wouldn't be environs 7.1.0 from the Pipfile.

Likewise, I hadn't changed the .env at all, so it should have already been a fresh copy of .env.example, as created by the post-install script: https://github.com/cookiecutter-flask/cookiecutter-flask/blob/1fd2de23a91f4361768b5fb46f6c7a3c0457428a/hooks/post_gen_project.py#L33

I'll run the above test inside the virtualenv and get back to you :)

**Comment by mbennett-uoe** [comment]
I can confirm environs is v7.1.0 and that `cp .env.example .env` produces the same error.

The example above runs perfectly inside the virtualenv :-/
```
(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ cat environs_test.py 
from tempfile import NamedTemporaryFile

import pytest
from environs import Env, EnvValidationError # environs==7.1.0

with NamedTemporaryFile() as temp:
    temp.write(b"A=foo\n")
    temp.write(b"B=123 # with a comment\n")
    env = Env()
    env.read_env(temp.name)


with pytest.raises(EnvValidationError):
    assert env.int("A")  # Expected to fail
    assert env.int("B") == 123
(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ python3 environs_test.py 
(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$
 ```

**Comment by mbennett-uoe** [comment]
Weirdly, it doesn't seem to be reading the temporary env correctly:
```(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ cat environs_test.py 
from tempfile import NamedTemporaryFile
import os
import pytest
from environs import Env, EnvValidationError # environs==7.1.0

with NamedTemporaryFile() as temp:
    temp.write(b"A=foo\n")
    temp.write(b"B=123 # with a comment\n")
    env = Env()
    env.read_env(temp.name)
    print("filename:", temp.name)
    print("file exists:", os.path.isfile(temp.name))
    print(env)

with pytest.raises(EnvValidationError):
    assert env.int("A")  # Expected to fail
    assert env.int("B") == 123
(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ python3 environs_test.py 
filename: /tmp/tmpsif8f_fi
file exists: True
<Env {}>
(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ 
```

**Comment by mbennett-uoe** [comment]
Further testing showed that nothing was being written to the temporary file(?!?). Modifying the script to close the file after the writes made sure there was data in the file, but the `env.read_env` call is still returning a blank object:

```(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ cat environs_test.py 
from tempfile import NamedTemporaryFile
import os
import pytest
from environs import Env, EnvValidationError # environs==7.1.0

with NamedTemporaryFile(delete=False) as temp:
    temp.write(b"A=foo\n")
    temp.write(b"B=123 # with a comment\n")
    temp.close()
    env = Env()
    env.read_env(temp.name)
    print("filename:", temp.name)
    print("file exists:", os.path.isfile(temp.name))
    print("file contents:", open(temp.name, "r").read())
    print(env)

with pytest.raises(EnvValidationError):
    assert env.int("A")  # Expected to fail
    assert env.int("B") == 123

(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ python3 environs_test.py 
filename: /tmp/tmp_o5582mq
file exists: True
file contents: A=foo
B=123 # with a comment

<Env {}>
(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ 
```

**Comment by mbennett-uoe** [comment]
There is something super wierd going on:

```
(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ echo "A=123" > test.env
(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from environs import Env
>>> env = Env()
>>> env.read_env("test.env", recurse=False)
>>> env
<Env {}>
>>> 
(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ cat test.env
A=123
(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ 
```

**Comment by jamescurtin** [comment]
Quite unusual that you’re seeing this problem persist. To your last post, I think you should be able to access the variables by doing something like `env.int(“A”)` rather than just `env`. 

Will merge in the PR in case others are having the same issue, though environs should theoretically be able to handle the comments.

**Comment by mbennett-uoe** [comment]
Deleted a bunch of comments because I was being stupid. of course without reading the variables from the file, the `Env` object doesn't see them.

**Comment by mbennett-uoe** [comment]
The test with the asserts is still not failing on the `assert env.int("A")  # Expected to fail` line, which is odd.

**Comment by mbennett-uoe** [comment]
But this does produce the expected error:

```
from tempfile import NamedTemporaryFile
import os
import pytest
from environs import Env, EnvValidationError # environs==7.1.0

with NamedTemporaryFile(delete=False) as temp:
    temp.write(b"A=foo\n")
    temp.write(b"B=123 # with a comment\n")
    temp.close()
    env = Env()
    env.read_env(temp.name, recurse=False)
    _, _ = env.int("A"), env.int("B")
```

```(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ python environs_test.py 
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 901, in _validated
    return self._format_num(value)
  File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 891, in _format_num
    return self.num_type(value)
ValueError: invalid literal for int() with base 10: 'foo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/environs/__init__.py", line 84, in method
    value = field.deserialize(value)
  File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 351, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 920, in _deserialize
    return self._validated(value)
  File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 946, in _validated
    return super()._validated(value)
  File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/marshmallow/fields.py", line 903, in _validated
    raise self.make_error("invalid", input=value) from error
marshmallow.exceptions.ValidationError: Not a valid integer.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "environs_test.py", line 12, in <module>
    _, _ = env.int("A"), env.int("B")
  File "/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/lib/python3.6/site-packages/environs/__init__.py", line 89, in method
    ) from error
environs.EnvValidationError: Environment variable "A" invalid: Not a valid integer.
```

**Comment by mbennett-uoe** [comment]
And getting rid of that line and replacing it with `print(env.int("B"))` works fine and correctly produces "123"

**Comment by mbennett-uoe** [comment]
I've just reproduced the issue on a clean (Ubuntu 18.04) VM. Full steps from the start:

- Installed python3 (3.6.9) from distro repo
- Installed nodejs 12 from nodesource package repo
- `pip3 install pipenv`
- `pip3 install cookiecutter`
- `cookiecutter https://github.com/cookiecutter-flask/cookiecutter-flask.git`
```
full_name [Steven Loria]: mike test
email [sloria1@gmail.com]: tes@test.test
github_username [sloria]: mbennett-uoe
project_name [My Flask App]: test app
app_name [test_app]: 
project_short_description [A flasky app.]: 
Select use_pipenv:
1 - no
2 - yes
Choose from 1, 2 (1, 2) [1]: 2
Select python_version:
1 - 3.8
2 - 3.7
3 - 3.6
Choose from 1, 2, 3 (1, 2, 3) [1]: 3
Select node_version:
1 - 12
2 - 10
Choose from 1, 2 (1, 2) [1]: 1
Select use_heroku:
1 - no
2 - yes
Choose from 1, 2 (1, 2) [1]: 1
```
- `cd test_app`
- `pipenv install --dev`
- `pipenv shell`
- `npm install`
- Edited the .env file to put the comment back on the same line as the variable declaration
- `npm start`

**Comment by mbennett-uoe** [comment]
AHA! I think I have it. The culprit is a combination of pipenv and environs. When you run pipenv, either for `shell` or `run` commands, it loads the values from `.env` into the system environment variables, and `environs` does not override them from the file if they are set already. (n.b: I've removed some of the output from the `env` command for security/readability)

```
ubuntu@bre:~/bre_card_catalogue$ pipenv shell
Loading .env environment variables…
Launching subshell in virtual environment…
ubuntu@bre:~/bre_card_catalogue$  . /home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe/bin/activate
(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ env
FLASK_APP=autoapp.py
LANG=C.UTF-8
OLDPWD=/home/ubuntu
FLASK_DEBUG=1
VIRTUAL_ENV=/home/ubuntu/.local/share/virtualenvs/bre_card_catalogue-1grt2ZLe
SECRET_KEY=not-so-secret
LOG_LEVEL=debug
XDG_SESSION_ID=1
FLASK_ENV=development
USER=ubuntu
PIP_PYTHON_PATH=/usr/bin/python3
PWD=/home/ubuntu/bre_card_catalogue
GUNICORN_WORKERS=1
DATABASE_URL=sqlite:////tmp/dev.db
PIPENV_ACTIVE=1
SEND_FILE_MAX_AGE_DEFAULT=0 # In production, set to a higher number, like 31556926
LESSOPEN=| /usr/bin/lesspipe %s
_=/usr/bin/env

(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ python
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from environs import Env
>>> env = Env()
>>> env.read_env()
>>> env("FLASK_ENV")
'development'
>>> exit()

(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ sed -i 's/development/developmentTEST/g' .env
(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ cat .env
# Environment variable overrides for local developmentTEST
FLASK_APP=autoapp.py
FLASK_DEBUG=1
FLASK_ENV=developmentTEST
DATABASE_URL=sqlite:////tmp/dev.db
GUNICORN_WORKERS=1
LOG_LEVEL=debug
SECRET_KEY=not-so-secret
SEND_FILE_MAX_AGE_DEFAULT=0 # In production, set to a higher number, like 31556926

(bre_card_catalogue) ubuntu@bre:~/bre_card_catalogue$ python
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from environs import Env
>>> env = Env()
>>> env.read_env()
>>> env("FLASK_ENV")
'development'
>>> 
```

**Comment by mbennett-uoe** [comment]
So I've walked back through `environs` and it provides access to the `override` argument in the call to the underlying `python-dotenv` function `load_dotenv()`.

This means the issue can be resolved by changing https://github.com/cookiecutter-flask/cookiecutter-flask/blob/df6dad13bae69e2f2f02de9e83c3b4f0d5ebf15b/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/settings.py#L12 to include "override=True" in the function call.

For people using pipenv, this will prevent the error occurring, but i leave it up to you as to whether it should be default behaviour for all users of the cookiecutter :)

**Comment by mbennett-uoe** [comment]
In the meantime, I've open an issue with pipenv here: https://github.com/pypa/pipenv/issues/4077 but looking at the activity on the repo (especially https://github.com/pypa/pipenv/issues/4058) it doesn't look promising that it will be resolved there any time soon.

**Comment by mbennett-uoe** [comment]
And here is a PR to implement https://github.com/cookiecutter-flask/cookiecutter-flask/issues/660#issuecomment-567926914 for users who choose "yes" to "Select use_pipenv" during the inital cookiecutter setup

**Comment by jamescurtin** [comment]
Expert sleuthing! In the short term, new users of the pipenv setup shouldn't run into issues, as your last PR moved the comment to the line above the env var. 

I would prefer to hold off on the #662 for now, as the override behavior may be unexpected given locally set env vars are expected to take precidence over what's in the config file. (Will close in a min, but thanks very much for digging in to find this issue!)

One potential alternative from the [advanced instructions](https://github.com/pypa/pipenv/blob/e6cabe649a50edc0cc883f5e9659f8931108835f/docs/advanced.rst#L354) for Pipenv that would achieve the same result without needing to set an override:

>To prevent pipenv from loading the .env file, set the PIPENV_DONT_LOAD_ENV environment variable:
`$ PIPENV_DONT_LOAD_ENV=1 pipenv shell`

What do you think? Might this work for your use case?

**Comment by mbennett-uoe** [comment]
I think that should work fine, as the .env is only really there for the flask app, and I am not using it for bringing in any other environment variables via pipenv. I'll give it a try and see how it works :)

**Comment by mbennett-uoe** [comment]
Happy to confirm that the above approach works ok and prevents the issue from occurring.

Consequently, I have changed the package.json file to include the PIPENV_DONT_LOAD_ENV=1 at the start of the `flask-server` and `flask-static-digest` scripts and added a new script for launching `pipenv shell` with the same.

Thanks for your help looking into and resolving this issue :) Happy new year!
