### ISSUE TITLE
Error: Cannot find module '@babel/preset-env' from '/app'

### ISSUE THREAD

**Issue by ivanfr90** [cookiecutter-flask/cookiecutter-flask#700]
Hi cookiecutters!

I'm currently using the last version of the repo with Docker to run the app and I'm getting an error related with the babel loader.
I have seen that commit b9766ad8b2915172f3a33745c0a9d320e2af766c fix the issue [#666](https://github.com/cookiecutter-flask/cookiecutter-flask/issues/666) and changes the presets from `["env"]` to `["@babel/preset-env"]` but in my environment this produces the below error. If I revert the changes and use the preset `["env"]` again all runs fine both in flask-dev and flask-pro.

Error using `docker-compose up flask-dev`:

> flask-dev_1   | [WEBPACK] ERROR in ./assets/js/main.js
flask-dev_1   | [WEBPACK] Module build failed (from ./node_modules/babel-loader/lib/index.js):
flask-dev_1   | [WEBPACK] Error: Cannot find module '@babel/preset-env' from '/app'
flask-dev_1   | [WEBPACK]     at Function.resolveSync [as sync] (/app/node_modules/resolve/lib/sync.js:81:15)
flask-dev_1   | [WEBPACK]     at resolveStandardizedName (/app/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
flask-dev_1   | [WEBPACK]     at resolvePreset (/app/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
flask-dev_1   | [WEBPACK]     at loadPreset (/app/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
flask-dev_1   | [WEBPACK]     at createDescriptor (/app/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
flask-dev_1   | [WEBPACK]     at /app/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
flask-dev_1   | [WEBPACK]     at Array.map (<anonymous>)
flask-dev_1   | [WEBPACK]     at createDescriptors (/app/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
flask-dev_1   | [WEBPACK]     at createPresetDescriptors (/app/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
flask-dev_1   | [WEBPACK]     at /app/node_modules/@babel/core/lib/config/config-descriptors.js:58:104
flask-dev_1   | [WEBPACK]     at cachedFunction (/app/node_modules/@babel/core/lib/config/caching.js:62:27)
flask-dev_1   | [WEBPACK]     at cachedFunction.next (<anonymous>)
flask-dev_1   | [WEBPACK]     at evaluateSync (/app/node_modules/gensync/index.js:244:28)
flask-dev_1   | [WEBPACK]     at sync (/app/node_modules/gensync/index.js:84:14)
flask-dev_1   | [WEBPACK]     at presets (/app/node_modules/@babel/core/lib/config/config-descriptors.js:29:84)
flask-dev_1   | [WEBPACK]     at mergeChainOpts (/app/node_modules/@babel/core/lib/config/config-chain.js:320:26)
flask-dev_1   | [WEBPACK]     at /app/node_modules/@babel/core/lib/config/config-chain.js:283:7
flask-dev_1   | [WEBPACK]     at Generator.next (<anonymous>)
flask-dev_1   | [WEBPACK]     at buildRootChain (/app/node_modules/@babel/core/lib/config/config-chain.js:68:36)
flask-dev_1   | [WEBPACK]     at buildRootChain.next (<anonymous>)
flask-dev_1   | [WEBPACK]     at loadPrivatePartialConfig (/app/node_modules/@babel/core/lib/config/partial.js:95:62)
flask-dev_1   | [WEBPACK]     at loadPrivatePartialConfig.next (<anonymous>)
flask-dev_1   | [WEBPACK]     at Function.<anonymous> (/app/node_modules/@babel/core/lib/config/partial.js:120:25)
flask-dev_1   | [WEBPACK]     at Generator.next (<anonymous>)
flask-dev_1   | [WEBPACK]     at evaluateSync (/app/node_modules/gensync/index.js:244:28)
flask-dev_1   | [WEBPACK]     at Function.sync (/app/node_modules/gensync/index.js:84:14)
flask-dev_1   | [WEBPACK]     at Object.<anonymous> (/app/node_modules/@babel/core/lib/config/index.js:41:61)
flask-dev_1   | [WEBPACK]     at Object.<anonymous> (/app/node_modules/babel-loader/lib/index.js:144:26)
flask-dev_1   | [WEBPACK]     at Generator.next (<anonymous>)
flask-dev_1   | [WEBPACK]     at asyncGeneratorStep (/app/node_modules/babel-loader/lib/index.js:3:103)

Project configuration:

|      Option                              |                                Values                                 |
|------------------------------------------|-----------------------------------------------------------------------|
| `use_pipenv`                             | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                      |
| `python_version`                         | <ul><li>- [X] `3.8`</li><li>- [ ] `3.7`</li><li>- [ ] `3.6`</li></ul> |
| `node_version`                           | <ul><li>- [X] `12`</li><li>- [ ] `10`</li></ul>                       |
| `use_heroku`                             | <ul><li>- [ ] `yes`</li><li>- [X] `no`</li></ul>                      |
| Are you using Docker to run the app?     | <ul><li>- [X] `yes`</li><li>- [ ] `no`</li></ul>                      |

**Comment by jamescurtin** [comment]
Hi @ivanfr90--thanks for your issue, and sorry for the delay! 

I am unable to reproduce your issue when doing a clean install. It sounds like you have generated a template both before and after this change. It's possible that when you upgraded to the most recent commit, your application was using an old cached set of node modules that did not contain the new `@babel/preset-env` module. 

You should be able to see what volumes currently exist by running `docker volume ls`. Assuming your project is called `my_flask_app`, the relevant volume would be called `my_flask_app_node-modules`. What happens if you first delete this volume then re-build the `flask-dev` image? It will force npm to do a fresh install that I suspect will solve your issue.
