### ISSUE TITLE
Typical workflow for new project?

### ISSUE THREAD

**Issue by boldandbusted** [cookiecutter-flask/cookiecutter-flask#713]
Howdy. I'm kicking the tires on cookiecutter-flask for a new personal project I'm working on with some folks. Once the new application directory is created with the shell script you provide, how is a typical user expected to store that directory? Should that new application directory become a Git Submodule under a fork of this repo, or 'git add'ed to a fork of this repo? Should we use a "multiple git remotes" approach to upgrading this repo (where we have remotes pointing to our fork, and remotes pointing here to this repo)?

I humbly suggest that this sort of thing be added to the README.md as a "Day 2" workflow suggestion, beyond the initial "Hello World" Day 0. :)

Thanks in advance for your guidance. Hope I'm making sense and this is the best way to communicate my request. Cheers! And thanks for cookiecutter-flask! :)

**Comment by jamescurtin** [comment]
Hey @boldandbusted! 

The projects that are created should be housed independently of the template. In general, it's probably not necessary to fork the template repo either, unless you're planning on making a contribution back to the template itself. 

Assuming you have created a project called `my-new-flask-app`, the general process to add the project to version control would be:

```console
$ mv my-new-flask-app /path/to/your/projects
$ cd /path/to/your/projects/my-new-flask-app
$ git init
$ git add .
$ git commit -m "Initial commit"
```

Then assuming you're going to store your code on Github, create a new repo on Github and follow the instructions to add the remote to your local repo.

Good luck with your new project!
