### ISSUE TITLE
Unable to run docker-compose

### ISSUE THREAD

**Issue by murilobellatini** [cookiecutter-flask/cookiecutter-flask#720]
Hello everyone!

I'm trying to run the `docker-compose` and getting the error below...

Can anyone shine a light 💡  on this matter?

Thanks!

Murilo

```python
$ docker-compose up flask-dev
Recreating twitter_explorer_flask-dev_1 ... done
Attaching to twitter_explorer_flask-dev_1
flask-dev_1   | Traceback (most recent call last):
flask-dev_1   |   File "/usr/local/bin/pipenv", line 8, in <module>
flask-dev_1   |     sys.exit(cli())
flask-dev_1   |   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
flask-dev_1   |     return self.main(*args, **kwargs)
flask-dev_1   |   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
flask-dev_1   |     rv = self.invoke(ctx)
flask-dev_1   |   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
flask-dev_1   |     return _process_result(sub_ctx.command.invoke(sub_ctx))
flask-dev_1   |   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
flask-dev_1   |     return ctx.invoke(self.callback, **ctx.params)
flask-dev_1   |   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
flask-dev_1   |     return callback(*args, **kwargs)
flask-dev_1   |   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
flask-dev_1   |     return ctx.invoke(f, obj, *args, **kwargs)
flask-dev_1   |   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
flask-dev_1   |     return callback(*args, **kwargs)
flask-dev_1   |   File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 408, in run
flask-dev_1   |     command=command, args=args, three=state.three, python=state.python, pypi_mirror=state.pypi_mirror
flask-dev_1   |   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 2310, in do_run
flask-dev_1   |     three=three, python=python, validate=False, pypi_mirror=pypi_mirror,
flask-dev_1   |   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 567, in ensure_project
flask-dev_1   |     project.touch_pipfile()
flask-dev_1   |   File "/usr/local/lib/python3.7/site-packages/pipenv/project.py", line 677, in touch_pipfile
flask-dev_1   |     with open("Pipfile", "a"):
flask-dev_1   | PermissionError: [Errno 13] Permission denied: 'Pipfile'
twitter_explorer_flask-dev_1 exited with code 1
```

Project configuration:

|      Option                              |                                Values                                 |
|------------------------------------------|-----------------------------------------------------------------------|
| `use_pipenv`                             | <ul><li>- [x] `yes`</li><li>- [ ] `no`</li></ul>                      |
| `python_version`                         | <ul><li>- [ ] `3.8`</li><li>- [ ] `3.7`</li><li>- [x] `3.6`</li></ul> |
| `node_version`                           | <ul><li>- [ ] `12`</li><li>- [x] `10`</li></ul>                       |
| `use_heroku`                             | <ul><li>- [ ] `yes`</li><li>- [x] `no`</li></ul>                      |
| Are you using Docker to run the app?     | <ul><li>- [x] `yes`</li><li>- [ ] `no`</li></ul>                      |

**Comment by jamescurtin** [comment]
Hi, @murilobellatini, thanks for your issue! A few questions:

Has your app run without this issue in the past, or is this your first time running the app?

I created a fresh project using the configuration you specified and could not reproduce; could you try rebuilding the image (`docker-compose build flask-dev`) and try running again to make sure that's not at issue?

I don't think this is related, but the log says the container is running Python 3.7, but the config options specify 3.6. Was this intentional?
