### ISSUE TITLE
Fix docker-compose manage image fails on apt-get

### ISSUE THREAD

**Issue by mhadam** [cookiecutter-flask/cookiecutter-flask#736]
Using a default configuration and running locally through Docker, this command fails:
`docker-compose run --rm manage db init`

With log:
```
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cyrus-sasl2/libsasl2-modules-db_2.1.27+dfsg-1_amd64.deb  404  Not Found [IP: 199.232.64.204 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cyrus-sasl2/libsasl2-2_2.1.27+dfsg-1_amd64.deb  404  Not Found [IP: 199.232.64.204 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/l/linux/linux-libc-dev_4.19.67-2_amd64.deb  404  Not Found [IP: 199.232.64.204 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cyrus-sasl2/libsasl2-modules_2.1.27+dfsg-1_amd64.deb  404  Not Found [IP: 199.232.64.204 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

It's fixed by using `--fix-missing` in `Dockerfile` lines:
```
RUN apt-get update --fix-missing
RUN apt-get install -y \
    curl \
    gcc
```

**Comment by jamescurtin** [comment]
Could you try re-building the `manage` service from scratch? You may have run into a transient failure when pulling the dependencies; I am unable to reproduce.

**Comment by mhadam** [comment]
Yea it is a weird transient thing. I'm not sure if it's possible that building/running flask-dev first somehow puts the manage service build in a bad state (re-using a cached layer? - it would seem so from the build log for the `apt-get upgrade` line).

I'm going to assume that adding `--fix-missing` works primarily because the command changes, forcing a rebuild.

In any case, the build does work with `docker-compose build --no-cache manage`. Might be worth adding this to documentation in case anyone else gets tripped up by it.
