### ISSUE TITLE
Document that the project uses port 5000

### ISSUE THREAD

**Issue by stodge** [cookiecutter-flask/cookiecutter-flask#757]
I ran `docker-compose up` but it failed as I already have something running on port 5000. I had to manually remove the docker images before I could re-run `docker-compose up`. Perhaps you could add a note to the README that the project uses 5000 and you should change several files to choose a different port? Just a minor suggestion. Cheers.

**Comment by jamescurtin** [comment]
Hi @stodge, thanks for your issue! It's important to note the distinction between the internal port of the service and the port that Docker uses to expose the app to the host machine.

In the project's [`docker-compose.yml`](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/ddb79534394cd0cf8cdd134d0df0cdfc3a745123/%7B%7Bcookiecutter.app_name%7D%7D/docker-compose.yml#L22) file, the container port is mapped to the host port in the order `HOST:CONTAINER`.

Therefore, if you want to change the port on which the project is exposed to, for example, `8080`, you can change this line from `5000:5000` to `8080:5000` without any other changes necessary to the rest of the application.

**Comment by stodge** [comment]
Oh good point! Thanks.
