### ISSUE TITLE
Create default admin user in the database during bootstrap

### ISSUE THREAD

**Issue by stodge** [cookiecutter-flask/cookiecutter-flask#759]
I think it would be useful to populate a default admin user in the database during the bootstrap. This could be specific to the dev environment, but I think it would also be useful for production too.

Perhaps:

```
docker-compose run --rm manage createadmin
```

I'm coming at this as a Django user. Cheers

**Comment by jamescurtin** [comment]
Thanks for the suggestion!

By default, the project comes with a `sqlite` database, which does not require authentication. Authentication is important for a production system, but `sqlite` is only suitable for development purposes, so I'd prefer not to add support for something like this, which might give the illusion it could be used in production.

On the other hand, I think it would be reasonable to add a question to the Cookiecutter template so users can chose between a fully featured DB like Postgres (which comes with support for creating an admin user out of the box) or the basic sqlite. We should provide the sqlite option for non-docker users, as running a database outside of docker is not trivial and is a barrier to someone who just wants to test out the project. I don't have the time to add this now, but feel free to submit a PR if this is functionality you'd like to help contribute to.

**Comment by stodge** [comment]
Apologies; I didn't explain myself very well. I'm trying to do too many things at once today. I meant an admin user IN the database. Not a user to access the database.
