### ISSUE TITLE
Question: how can you change the template?

### ISSUE THREAD

**Issue by fadikatrina** [cookiecutter-flask/cookiecutter-flask#873]
Sorry for the amateur question but can you please tell me how to change the default template given? For example, I am trying to change it to this one https://themekita.com/demo-atlantis-lite-bootstrap/.

Thanks a lot. If this is not the place for this kind of question let me know and I'll post it somewhere else.

**Comment by jamescurtin** [comment]
Hi @fadikatrina:

If you're following the [quick start](https://themekita.com/demo-atlantis-lite-bootstrap/livepreview/documentation/) guide for the theme you linked above, you could add the required CSS and JS components to [`layout.html`](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/templates/layout.html).

All other HTML lives in the [`templates`](https://github.com/cookiecutter-flask/cookiecutter-flask/tree/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/templates) directory, so you may need to go through and customize these files to get the styling the way you want it.

**Comment by fadikatrina** [comment]
Hi @jamescurtin thanks for the reply.

I did try that indeed but it did not work properly (the styling looked weird) and I really was not sure why. But I tried a different theme (https://startbootstrap.com/themes/sb-admin-2/) and it worked, so I think it was because the atlantis one was a free version so did not have all the required css.

Thanks again, will close
