### ISSUE TITLE
flask-prod_1  | Error: Cannot find module 'uglifyjs-webpack-plugin'

### ISSUE THREAD

**Issue by AcademicDog** [cookiecutter-flask/cookiecutter-flask#888]
I have deployed two servers, but with the same docker configuration, only one works well.

Project configuration:

|      Option                              |                                Values                                 |
|------------------------------------------|-----------------------------------------------------------------------|
| `use_pipenv`                             | yes                      |
| `python_version`                         | 3.8 |
| `node_version`                           | 12                       |
| `use_heroku`                             | no                      |
| Are you using Docker to run the app?     | yes                      |
| | |
| Docker version     | 19.03.12|
| Docker-compose version|1.27.1|

I want to deploy a website with "uglifyjs-webpack-plugin". Here is my "webpack.config.js":
```
...
/*
 * Webpack Plugins
 */
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin'); // only import
...
```
And the "package.json" is
```
...
    "run-script-os": "^1.0.7",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "url-loader": "^4.0.0",
    "webpack": "^4.33.0",
    "webpack-cli": "^3.3.2"
...
```
By this configuration, the "uglifyjs-webpack-plugin" is installed and it can be found in "node_modules" folder.

I deployed with docker in two servers (different hosts), only one works well. And another is "flask-prod_1  | Error: Cannot find module 'uglifyjs-webpack-plugin'. Here is the log:
```
flask-prod_1  | > NODE_ENV=production webpack --progress --colors -p && npm run flask-static-digest
flask-prod_1  |
flask-prod_1  | /app/node_modules/webpack-cli/bin/cli.js:93
flask-prod_1  |                                 throw err;
flask-prod_1  |                                 ^
flask-prod_1  |
flask-prod_1  | Error: Cannot find module 'uglifyjs-webpack-plugin'
flask-prod_1  | Require stack:
flask-prod_1  | - /app/webpack.config.js
flask-prod_1  | - /app/node_modules/webpack-cli/bin/utils/convert-argv.js
flask-prod_1  | - /app/node_modules/webpack-cli/bin/cli.js
flask-prod_1  | - /app/node_modules/webpack/bin/webpack.js
flask-prod_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
flask-prod_1  |     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
```
The two servers are both centos. One is 7.8.2003 (bad), another is 7.6.1810 (good). I just want to know what's the problem is.

**Comment by jamescurtin** [comment]
My guess is that in one case, the old node_modules are being cached. You could run something like:

```
docker volume rm <YOUR_APP_NAME>_node-modules
docker-compose build
```

which would remove the local volume containing the cached node modules, then re-build all images to pull in the changes you had made to `package.json`.
