### ISSUE TITLE
Foldering questions

### ISSUE THREAD

**Issue by psypersky** [cookiecutter-flask/cookiecutter-flask#899]
Hello dear writers of this cool repository

I have one question about the foldering structure of the app

- app_name
  - public
  - user

"public" refers to accessibility permissions

"user" refers to an abstract entity or a real life object

I've been expanding on your project structure like so

- app_name
  - public
  - user
  - admin
  - graphics

And I realized that this would mean that any public view should be in /public regardless of which entity belongs to, probably too much overthinking here, but wouldn't it make more sense to delete the public folder since we don't have a private one.

Thanks for the cool code! Have a great day :)

**Comment by jamescurtin** [comment]
Hey @psypersky --great question!

By default `user` and `public` are provided as the two default blueprints, but you should feel free to customize the blueprints based on your project.

In the default project, the [public views](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/public/views.py) would be accessible to any visitor to the site, without authentication. In contrast, the [user views](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/8cd28fa6769658c39f0eeb7eb08bd7491a41b2ac/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/user/views.py#L10) include the `@login_required` decorator, so only a logged in user would be able to see them. In this sense, they're organized as the "public" and the "private" blueprints.
