### ISSUE TITLE
Incorrect parameters passed to `webpack` inside `package.json`

### ISSUE THREAD

**Issue by Mogmi95** [cookiecutter-flask/cookiecutter-flask#955]
Hello there! Thanks for the awesome project.

I noticed those lines inside the `package.json` file,:
```javascript
"build:win32": "NODE_ENV=production webpack --progress --colors -p && npm run flask-static-digest",
"build:default": "NODE_ENV=production webpack --progress --colors -p && npm run flask-static-digest",
```
Which output some errors
```
> NODE_ENV=production webpack --progress --colors -p && npm run flask-static-digest

[webpack-cli] Unknown argument: --colors
Did you mean --color?
[webpack-cli] Unknown argument: -p
```
Which are probably legacy from a prior version of webpack-cli. According to the [webpack-cli documentation](https://www.npmjs.com/package/webpack-cli), they don't exist:
* `--colors` should be `--color`
* `-p` seems to be an option to create a template to create a plugin

It looks like there are no side effect to these changes, but the `-p` is worrying me a bit, maybe I'm missing something.

Hope it helps!

Project configuration:

|      Option                              |                                Values                                 |
|------------------------------------------|-----------------------------------------------------------------------|
| `use_pipenv`                             | <ul><li>- [ ] `yes`</li><li>- [x] `no`</li></ul>                      |
| `python_version`                         | <ul><li>- [x] `3.8`</li><li>- [ ] `3.7`</li><li>- [ ] `3.6`</li></ul> |
| `node_version`                           | <ul><li>- [x] `12`</li><li>- [ ] `10`</li></ul>                       |
| `use_heroku`                             | <ul><li>- [ ] `yes`</li><li>- [x] `no`</li></ul>                      |
| Are you using Docker to run the app?     | <ul><li>- [x] `yes`</li><li>- [ ] `no`</li></ul>                      |

**Comment by jaonewguy** [comment]
Hi, I'm noticing the same errors as well, and am wondering how to proceed "correctly".  Thanks in advance!

**Comment by jamescurtin** [comment]
Thanks for reporting! These changes were introduced by the upgrade to Webpack 5.x. You're correct about the change of `--colors` to `--color`. The `-p` option was, confusingly, an alias for `--optimization-minimize`.

This should be fixed in the PR referenced above. The PR also adds a step to the CI process that will catch a similar class of issues in the future. Sorry for the inconvenience!
